---
apiVersion: v1
kind: Namespace
metadata:
    name: ibm-common-services-hack
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-common-services-hack
  namespace: ibm-common-services-hack
spec:
  targetNamespaces:
  - ibm-common-services-hack
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-common-service-operator
  namespace: ibm-common-services-hack
spec:
  channel: v3
  installPlanApproval: Automatic
  name: ibm-common-service-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-common-service-operator.v3.8.0
