apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-mas-operators
  namespace: openshift-marketplace
spec:
  displayName: IBM MAS Catalog (Dev)
  publisher: IBM
  description: Catalog Source for IBM Maximo Application Suite (Internal Use Only)
  sourceType: grpc
  image: wiotp-docker-local.artifactory.swg-devops.com/cpopen/ibm-mas-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
