---
# tasks file for sls


# 1. Check for missing properties that do not have defaults
- name: "main: Fail if artifactory_username has not been provided"
  when: artifactory_username is not defined or artifactory_username == ""
  fail:
    msg: "artifactory_username property has not been set"

- name: "main: Fail if artifactory_apikey has not been provided"
  when: artifactory_apikey is not defined or artifactory_apikey == ""
  fail:
    msg: "artifactory_apikey property has not been set"


# 2. Provide debug information
- name: "Debug information"
  debug:
    msg:
     - "SLS catalog ................... {{ sls_catalog }}"
     - "SLS channel ................... {{ sls_channel }}"
     - "SLS namespace ................. {{ sls_namespace }}"
     - "Artifactory username .......... {{ artifactory_username }}"
     - "Artifactory apikey ............ ******************"

# 3. Run the setup tasks
- include_tasks: tasks/setup/catalog.yml
- include_tasks: tasks/setup/operator.yml
- include_tasks: tasks/setup/service.yml
