---
# 1. Fyre Login
# -----------------------------------------------------------------------------
- name: "login-quickburn : Fail if username is not provided"
  when: username is not defined
  fail:
    msg: "username property is required"

- name: "login-quickburn : Fail if password is not provided"
  when: password is not defined
  fail:
    msg: "password property is required"

- name: "login-quickburn : Get Cluster Details"
  uri:
    url: https://ocpapi.svl.ibm.com/v1/ocp/{{ cluster_name }}
    user: "{{ username }}"
    password: "{{ password }}"
    method: GET
    force_basic_auth: yes
    validate_certs: false
  register: _cluster_details

- set_fact:
    api_host: "api.{{ cluster_name }}.cp.fyre.ibm.com"
    _this_cluster: "{{ _cluster_details.json.clusters | selectattr('cluster_name', '==', cluster_name) | last }}"

- debug:
    var: api_ip

- name: "login-quickburn : Connect to API Host"
  shell: |
    ping -c 1 -t 5 "{{ api_host }}"
  register: _ping_result
  ignore_errors: true

- name: Request DNS configuration
  pause: 
    prompt: "Could not reach API Host, please set DNS or /etc/hosts so {{ api_host }} resolves to {{ api_ip }} "
  when: not _ping_result.rc == 0
  vars:
    api_ip: "{{ _this_cluster.vms |
              selectattr('hostname', '==', api_host) | map(attribute='ips') | last |
              selectattr('type', '==', 'public') | map(attribute='address') | last }}"

- name: "login-quickburn : Oc Login the created cluster"
  vars:
    login_password: "{{ _this_cluster.kubeadmin_password }}"
    login_server: "https://{{ api_host }}:6443"
  shell: |
    oc login -u kubeadmin -p {{ login_password }} --server={{ login_server }} --insecure-skip-tls-verify=true
