---
# 1. ROKS Login
# -----------------------------------------------------------------------------
- name: "login-roks : Fail if ibmcloud_apikey is not provided"
  when:
    - ibmcloud_apikey is not defined
  fail:
    msg: "ibmcloud_apikey property is required"

- name: "login-roks : Login to IBM Cloud"
  shell: |
    ibmcloud login --apikey "{{ ibmcloud_apikey }}" -q --no-region

- name: "login-roks : Set the target cluster"
  shell: |
    ibmcloud oc cluster config -c {{ cluster_name }} --admin
