---
# 1. Check that we have an IBM Cloud API key defined
# -----------------------------------------------------------------------------
- name: "login-roks : Fail if ibmcloud_apikey is not provided"
  when:
    - ibmcloud_apikey is not defined
  fail:
    msg: "ibmcloud_apikey property is required"


# 2. Login to IBM Cloud
# -----------------------------------------------------------------------------
# IBM Cloud login can be unreliable at times, so we wrap this call in a retry
# loop with a 1 minute cooldown between retries, after 10 attempts we will give
# up and the task will fail
- name: "login-roks : Login to IBM Cloud"
  shell: |
    ibmcloud login --apikey "{{ ibmcloud_apikey }}" -q --no-region
  retries: 10
  delay: 60


# 3. Configure for the selected cluster
# -----------------------------------------------------------------------------
- name: "login-roks : Set the target cluster"
  shell: |
    ibmcloud oc cluster config -c {{ cluster_name }} --admin
