---
# ───────────────────────────────────────────────────────────────────────────────
# Running Validation Checks...
# ───────────────────────────────────────────────────────────────────────────────
# Validating property values...
# Validating sitename...
# Validating namespace...
# Validating kubectl user...
# Validating encryption keyfile...
# Validating registry host...

# validation_check()
# {
#   header "Running Validation Checks..."
#   validate_property_names
#   validate_property_values
#   validate_sitename
#   validate_namespace
#   validate_kubectl_user
#   validate_encryption
#   validate_registry_host
#   validate_load_balancer_type
#   validate_load_balancer_ip

#   draw_line

#   echo ""
# }

- name: "Assert that mas_arcgis_namespace is provided"
  assert:
    that:
      - mas_arcgis_namespace is defined and mas_arcgis_namespace != ''
    fail_msg: "'mas_arcgis_namespace' property is not provided"

- name: "Assert that arcgis_container_registry_username is provided"
  assert:
    that:
      - arcgis_container_registry_username is defined and arcgis_container_registry_username != ''
    fail_msg: "'arcgis_container_registry_username' property is not provided"

- name: "Assert that arcgis_container_registry_password is provided"
  assert:
    that:
      - arcgis_container_registry_password is defined and arcgis_container_registry_password != ''
    fail_msg: "'arcgis_container_registry_password' property is not provided"
  
- name: "Create '{{ mas_arcgis_namespace }}' namespace"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/namespace.yml.j2"
