---
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Elasticsearch RBAC
# ───────────────────────────────────────────────────────────────────────────────
# serviceaccount/arcgis-elastic-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-elastic-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-elastic-rolebinding created
# [SUCCESS]

- name: Create elastic rbacs
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/elastic/elastic-rbac.yml.j2'
