---
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Admin API
# ───────────────────────────────────────────────────────────────────────────────
# Validating internal property values...
# configmap/arcgis-log-settings created
# secret/arcgis-spatiotemporal-index-store-info created
# secret/arcgis-env-variables created
# secret/arcgis-site-info created
# secret/arcgis-server-context created
# configmap/arcgis-config-last-modified created
# configmap/arcgis-queue-config created
# serviceaccount/arcgis-admin-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-admin-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-admin-rolebinding created
# deployment.apps/arcgis-rest-administrator-api created
# service/arcgis-rest-administrator-api created
# Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
# ingress.networking.k8s.io/arcgis-ingress-rest-administrator-api created
# [SUCCESS]

- name: "Load arcgis container image properties"
  include_vars: "vars/container-image-properties.yml.j2"

- name: "Load arcgis deployment resource properties"
  include_vars: "vars/deployment-resource-properties.yml.j2"

# Create arcgis-enterprise configmaps and secrets
# ------------------------------------------------------------------------------------------------------------------------------
- name: "Create arcgis-enterprise configmaps and secrets"
  vars:
    env_vars_json: 'templates/arcgis-enterprise/env-variables.json.j2'
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/arcgis-enterprise/base-config.yml.j2'


# Create arcgis-ingress-controller RBACs
# ------------------------------------------------------------------------------------------------------------------------------
- name: "Create arcgis-enterprise rbacs"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/arcgis-enterprise/rbac-config.yml.j2'

# Create  arcgis-ingress-controller deployment
# ------------------------------------------------------------------------------------------------------------------------------
- name: "Create '{{ arcgis_admin_deployment_name }}' deployment"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/arcgis-enterprise/arcgis-enterprise.yml.j2'

# Create  arcgis-ingress-controller ingress
# ------------------------------------------------------------------------------------------------------------------------------
- name: "Create '{{ arcgis_admin_service_name }}' service"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/arcgis-enterprise/arcgis-enterprise-service.yml.j2'
  
# Create  arcgis-ingress-controller service
# ------------------------------------------------------------------------------------------------------------------------------
- name: "Create '{{ arcgis_admin_ingress_name }}' ingress"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/arcgis-enterprise/arcgis-enterprise-ingress.yml.j2'
