---
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Manager
# ───────────────────────────────────────────────────────────────────────────────
# deployment.apps/arcgis-enterprise-manager created
# service/arcgis-enterprise-manager created
# Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
# ingress.networking.k8s.io/arcgis-ingress-enterprise-manager created
# [SUCCESS]

# Create arcgis-enterprise-manager deployment
# ------------------------------------------------------------------------------------------------------------------------------
- name: "Create '{{ arcgis_manager_deployment_name }}' deployment"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/arcgis-manager/arcgis-manager.yml.j2'

# Create arcgis-enterprise-manager service
# ------------------------------------------------------------------------------------------------------------------------------
- name: "Create '{{ arcgis_manager_service_name }}' service"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/arcgis-manager/arcgis-manager-service.yml.j2'

# Create arcgis-enterprise-manager ingress
# ------------------------------------------------------------------------------------------------------------------------------
- name: "Create '{{ arcgis_manager_ingress_name }}' ingress"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/arcgis-manager/arcgis-manager-ingress.yml.j2'

# Create arcgis-enterprise-manager route
# ------------------------------------------------------------------------------------------------------------------------------
- name: "Create '{{ arcgis_manager_ingress_name }}' route"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/arcgis-manager/route.yml.j2'
