---
# ───────────────────────────────────────────────────────────────────────────────
#            Deploy ArcGIS Enterprise 11.2 on Kubernetes (11.2.0.5207)
# ───────────────────────────────────────────────────────────────────────────────
# ───────────────────────────────────────────────────────────────────────────────
# Checking System Requirements...
# ───────────────────────────────────────────────────────────────────────────────
#     Checking operating system ......................................... WARNING
#         [33mMacOS is not a supported operating system.  Check the ArcGIS
#         Enterprise on Kubernetes System Requirements for supported
#         platforms.(B[m
#     Checking for kubectl .............................................. OK
#     Checking kubeconfig context ....................................... OK
#     Checking Kubernetes version ....................................... OK
#     Checking for support scripts ...................................... OK
#     Checking for arcgis-enterprise yaml ............................... OK
#     Checking for OpenSSL .............................................. OK
#     Checking for OS ................................................... OK
# ───────────────────────────────────────────────────────────────────────────────

# ───────────────────────────────────────────────────────────────────────────────
# Running Validation Checks...
# ───────────────────────────────────────────────────────────────────────────────
# Validating property values...
# Validating sitename...
# Validating namespace...
# Validating kubectl user...
# Validating encryption keyfile...
# Validating registry host...
# ───────────────────────────────────────────────────────────────────────────────

# ───────────────────────────────────────────────────────────────────────────────
# Creating Docker Secrets
# ───────────────────────────────────────────────────────────────────────────────
# secret/arcgis-container-registry created
# [SUCCESS]
# secret/arcgis-container-registry labeled
# [SUCCESS]
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Ingress Controller
# ───────────────────────────────────────────────────────────────────────────────
# Using OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
# .......+.........+.+...+.....+.+..+.........+.........+.+.....+++++++++++++++++++++++++++++++++++++++*...+.......+.........+...+..+......+...+.+.........+.....+......+++++++++++++++++++++++++++++++++++++++*.............+......+.+.....+..........+....................+.+.....+............+...............+............+.+...+............+...+...........+...+.......+...........+...+............+............+...+...+.+...........+.........+.+...+.....+......+.+..+.......+..................+..+..................................+..+...................+...+..+.........+.+......+..+.+............+.....+.......+......+.....................+...+..+......+..........+.....+....+......+...+......+.....+.+........+....+.....+...+........................+....+..+............+.+.........+...+..+...+....+........+.+.....+.+.....+.+...+..+....+...............+...+...+...+..+...+.......+..+.+.........+......+.....+.+......+...+...........+...+............+...+...+...+.+......+....................+...+.........+.+..+.........+......+.......+.....+.......+...............+.....+......+...+....+..+.+........+.+......+............+..+...+.+...........+....+.....+.+......++++++
# .....+++++++++++++++++++++++++++++++++++++++*..........+...+............+...+..+...+.+++++++++++++++++++++++++++++++++++++++*...+.....+...+.+.....+...+.+......+......+.....+...+.+.....+......+.........+.+...+...............+..+............+...+....+......+........+....+..+.........+......+....+.........+........+.......+........+.......+......+..+....+..................+......+....................+.+....................+......+.......+..+......+.........+...+...............+.+..............+.......++++++
# -----
# secret/arcgis-interpod-cert-pem created
# secret/arcgis-interpod-cert-pem labeled
# secret/arcgis-interpod-cert-pem labeled
# secret/arcgis-interpod-cert-pfx created
# secret/arcgis-interpod-cert-pfx labeled
# secret/arcgis-interpod-cert-pfx labeled
# .+..+.......+..+++++++++++++++++++++++++++++++++++++++*....+......+........+.......+...+............+..+...+.........+...+.......+......+...+......+.....+...+......+++++++++++++++++++++++++++++++++++++++*........+...+.+..............+...............+...+...+....+...+........+.......+.........+......+........+....+.................+.+.........+...+..++++++
# ..........+......+.....+............+.+......+...+.....+.+..+...+++++++++++++++++++++++++++++++++++++++*...+..+...+.+............+...+...............+++++++++++++++++++++++++++++++++++++++*......+..+...+..........+........+......+......+.........+.+............+..+.........+....+..+.+.................+.+..+...+.....................+....+.....+.+...........+....+......+..+.......+...+...+.....+............+..........+.....+.+..+...............+...+....+...+...+.....+......+....+.........+........+....+.........+............+..+...............+...+...+....+...+..+......+....+..+................+..+.+..+............++++++
# -----
# secret/arcgis-ingress-cert-pem created
# secret/arcgis-ingress-cert-pem labeled
# configmap/arcgis-ingress-controller-nginx-config created
# configmap/arcgis-ingress-controller-tcp-services created
# configmap/arcgis-ingress-controller-udp-services created
# lease.coordination.k8s.io/arcgis-ingress-controller-leader created
# serviceaccount/arcgis-ingress-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-ingress-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-ingress-rolebinding created
# deployment.apps/arcgis-ingress-controller created
# service/arcgis-ingress-nginx created
# [SUCCESS]
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Prometheus RBAC
# ───────────────────────────────────────────────────────────────────────────────
# serviceaccount/arcgis-prometheus-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-prometheus-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-prometheus-rolebinding created
# [SUCCESS]
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Queue Store RBAC
# ───────────────────────────────────────────────────────────────────────────────
# serviceaccount/arcgis-queue-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-queue-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-queue-rolebinding created
# [SUCCESS]
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Elasticsearch RBAC
# ───────────────────────────────────────────────────────────────────────────────
# serviceaccount/arcgis-elastic-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-elastic-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-elastic-rolebinding created
# [SUCCESS]
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Admin API
# ───────────────────────────────────────────────────────────────────────────────
# Validating internal property values...
# configmap/arcgis-log-settings created
# secret/arcgis-spatiotemporal-index-store-info created
# secret/arcgis-env-variables created
# secret/arcgis-site-info created
# secret/arcgis-server-context created
# configmap/arcgis-config-last-modified created
# configmap/arcgis-queue-config created
# serviceaccount/arcgis-admin-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-admin-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-admin-rolebinding created
# deployment.apps/arcgis-rest-administrator-api created
# service/arcgis-rest-administrator-api created
# Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
# ingress.networking.k8s.io/arcgis-ingress-rest-administrator-api created
# [SUCCESS]
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Help
# ───────────────────────────────────────────────────────────────────────────────
# service/arcgis-help created
# deployment.apps/arcgis-help created
# Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
# ingress.networking.k8s.io/arcgis-help-ingress created
# [SUCCESS]
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Manager
# ───────────────────────────────────────────────────────────────────────────────
# deployment.apps/arcgis-enterprise-manager created
# service/arcgis-enterprise-manager created
# Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
# ingress.networking.k8s.io/arcgis-ingress-enterprise-manager created
# [SUCCESS]

# Waiting for pods to startup...

# POD                                                  STATUS
# arcgis-rest-administrator-api-5b758794bb-dh6nk       Running
# arcgis-help-cdfb598b7-d88tp                          Running
# arcgis-enterprise-manager-59554bf9bc-sv9v2           Running
# arcgis-ingress-controller-6f857d5fdb-4cdg7           Running

# Waiting for site availability.......Ready
# ───────────────────────────────────────────────────────────────────────────────
#                            S U C C E S S !
# ───────────────────────────────────────────────────────────────────────────────
# ArcGIS Enterprise 11.2 on Kubernetes 11.2.0.5207 has been successfully deployed.

# Create the ingress or OpenShift route resource now, if you have not done so yet.

# The secure route should direct traffic to the arcgis-ingress-nginx service
# using either re-encrypt or passthrough for TLS termination.

# If using a DNS alias, you should create a CNAME record that resolves
# the DNS alias to the canonical router hostname for the cluster.

# Use the following URL to access the ArcGIS Enterprise 11.2 on Kubernetes
# Setup Wizard and configure your organization:

#     https://arcgis.apps.hpdevops.cp.fyre.ibm.com/arcgis/manager

# Use this URL to access ArcGIS Enterprise 11.2 on Kubernetes help:

#     https://arcgis.apps.hpdevops.cp.fyre.ibm.com/arcgis/help/en/

- name: "Checking system requirements (1/11)"
  include_tasks: "tasks/01-check-system-requirements.yml"

- name: "Running Validation Checks (2/11)"
  include_tasks: "tasks/02-run-validation-checks.yml"

- name: "Creating Docker Secrets (3/11)"
  include_tasks: "tasks/03-create-docker-secrets.yml"

- name: "Deploying Ingress Controller (4/11)"
  include_tasks: "tasks/04-deploy-ingress-controller.yml"

- name: "Deploying Prometheus RBAC (5/11)"
  include_tasks: "tasks/05-deploy-prometheus-rbac.yml"

- name: "Deploying Queue Store RBAC (6/11)"
  include_tasks: "tasks/06-deploy-queue-store-rbac.yml"

- name: "Deploying Elasticsearch rbac (7/11)"
  include_tasks: "tasks/07-deploy-elasticsearch-rbac.yml"

- name: "Deploying Admin API (8/11)"
  include_tasks: "tasks/08-deploy-admin-api.yml"

- name: "Deploying Help (9/11)"
  include_tasks: "tasks/09-deploy-help.yml"

- name: "Deploying Manager (10/11)"
  include_tasks: "tasks/10-deploy-manager.yml"

- name: "Waiting for pods to startup (11/11)"
  include_tasks: "tasks/11-wait-pods-startup.yml"

# Provide Arcgis Manager dashboard URL
# -----------------------------------------------------------------------------
- name: "Lookup '{{ arcgis_manager_ingress_name }}' route"
  kubernetes.core.k8s_info:
    kind: Route
    api_version: route.openshift.io/v1
    name: "{{ arcgis_ingress_controller_service_name }}"
    namespace: "{{ arcgis_namespace }}"
  register: arcgis_manager_route_lookup

- assert:
    that:
      - arcgis_manager_route_lookup.resources is defined
      - arcgis_manager_route_lookup.resources | length > 0
      - arcgis_manager_route_lookup.resources[0].spec is defined
      - arcgis_manager_route_lookup.resources[0].spec.host is defined
    fail_msg: "Route '{{ arcgis_ingress_controller_service_name }}' was not found under '{{ arcgis_namespace }}' namespace!"

- set_fact:
    arcgis_manager_route: "https://{{ arcgis_manager_route_lookup.resources[0].spec.host }}"


- name: "Arcgis installation finished successfully!"
  debug:
    msg:
      - "Use the following URL to access the ArcGIS Enterprise 11.2 on Openshift and configure your organization:"
      - ""
      - "{{ arcgis_manager_route }}/arcgis/manager"
