- hosts: infra_nodes
  tasks:
    - name: Copy the script to the infra node
      copy:
        src: ./../files/enableIPv6.sh
        dest: /tmp/enableIPv6.sh
        mode: 0755

    - name: Run the script on the infra node
      shell: /tmp/enableIPv6.sh
