---
# tasks file for suite

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if instance_id is not provided"
  when: instance_id is not defined or instance_id == ""
  fail:
    msg: "instance_id property is required"

# 2. Provide debug information
# -----------------------------------------------------------------------------
- name: "Configure namespace"
  set_fact:
    mas_namespace: "mas-{{ instance_id }}-core"

- name: "Debug information"
  debug:
    msg:
      - "Instance ID ............... {{ instance_id }}"
      - "MAS namespace ............. {{ mas_namespace }}"

- name: "Apply configs"
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', item) }}"
  with_items: "{{ mas_config }}"
