---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # Choose which catalog source to use for the MAS install, default to the IBM operator catalog
    mas_catalog_source: "{{ lookup('env', 'MAS_CATALOG_SOURCE') | default('ibm-operator-catalog', true) }}"

    # --- Dev catalog settings ----------------------------------------------------------------------------------------
    # Only required when using the development catalog sources for pre-release installation
    # These are used to set up image pull secret in the openshift-marketplace namespace
    artifactory_username: "{{ lookup('env', 'W3_USERNAME') | lower }}"
    artifactory_apikey: "{{ lookup('env', 'ARTIFACTORY_APIKEY') }}"
    # -----------------------------------------------------------------------------------------------------------------

    # Which MAS channel to subscribe to
    mas_channel: "{{ lookup('env', 'MAS_CHANNEL') | default('8.x', true) }}"

    # MAS configuration
    # custom_domain: "{{ lookup('env', 'DOMAIN') }}"
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"

    # MAS configuration - IBM container registry configuration
    # Set both of these to wiotp-docker-local.artifactory.swg-devops.com for dev
    mas_icr_cp: "{{ lookup('env', 'MAS_ICR_CP') | default('cp.icr.io/cp', true) }}"
    mas_icr_cpopen: "{{ lookup('env', 'MAS_ICR_CPOPEN') | default('icr.io/cpopen', true) }}"

    # MAS configuration - Entitlement
    mas_entitlement_username: "{{ lookup('env', 'MAS_ENTITLEMENT_USERNAME') | default('cp', true) }}"
    mas_entitlement_key: "{{ lookup('env', 'MAS_ENTITLEMENT_KEY') }}"

    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') | default('~/maximoappsuite/devops-configs/config', true) }}"
    mas_config:
      - "{{ mas_config_dir }}/bascfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/slscfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/mongocfg_masdev.yaml"
      - "{{ mas_config_dir }}/smtpcfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/ldapcfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/workspace_masdev.yaml"

  roles:
    - mas.devops.suite_install
    - mas.devops.suite_config
    - mas.devops.suite_verify
