# mkdocs serve

site_name: MAS Devops Collection

repo_name: GitHub
repo_url: https://github.ibm.com/maximoappsuite/mas-devops-ansible
edit_uri: blob/master/docs/

nav:
  - 'Home': index.md
  - 'Playbooks':
    - 'Full Stack on IBM Cloud': playbooks/fullstack-roks.md
    - 'Full Stack on QuickBurn': playbooks/fullstack-quickburn.md
    - 'OCP Playbooks': playbooks/ocp.md
    - 'Dependencies Playbooks': playbooks/dependencies.md
    - 'CP4D Playbooks': playbooks/cp4d.md
    - 'MAS Playbooks': playbooks/mas.md
  - 'Roles':
    - 'OCP Roles': roles/ocp.md
    - 'Dependencies Roles': roles/dependencies.md
    - 'CP4D Roles': roles/cp4d.md
    - 'MAS Roles': roles/mas.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      permalink: 
  - admonition
  # Add this to support expandable sections
  #- pymdownx.details

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# Note
# Abstract
# Info
# Tip
# Success
# Question
# Warning
# Failure
# Danger
# Bug
# Example
# Quote