---
- name: "Install minio namespace"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/namespace.yml.j2') }}"

- name: "Install minio deployment"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/deployment.yml.j2') }}"

- name: "Install minio pvc"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/pvc.yml.j2') }}"

- name: "Install minio route"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/route.yml.j2') }}"

- name: "Install minio service"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/service.yml.j2') }}"
