---
# Lookup CPD credentials
# -----------------------------------------------------------------------------
# The following secret will only exist if installing from CPD 4.8.x, if upgrading from 4.6.x it will continue using 'admin_user_details' secret
- name: "get-cpd-details : Lookup Cloud Pak for Data admin username"
  shell: |
    oc get secret ibm-iam-bindinfo-platform-auth-idp-credentials -n {{ cpd_instance_namespace }} -o json | jq -r '.data.admin_username' | base64 -d
  register: cpd_admin_username_output

- name: "get-cpd-details : Lookup Cloud Pak for Data admin url"
  shell: |
    oc get ZenService lite-cr -o jsonpath="{.status.url}{'\n'}" -n {{ cpd_instance_namespace }}
  register: cpd_admin_url_output
  failed_when: cpd_admin_url_output.stdout | length == 0

- name: "get-cpd-details : Set Cloud Pak for Data credentials if installing from 4.6.x"
  set_fact:
    cpd_admin_username: "admin"
    cpd_admin_password: "Found in 'admin_user_details' secret under '{{ cpd_instance_namespace }}' namespace"
    cpd_admin_url: "{{ cpd_admin_url_output.stdout }}"
  when: cpd_admin_username_output.stdout | length == 0

- name: "get-cpd-details : Set Cloud Pak for Data credentials if installing from 4.8.x"
  set_fact:
    cpd_admin_username: "cpadmin"
    cpd_admin_password: "Found in 'ibm-iam-bindinfo-platform-auth-idp-credentials' secret under '{{ cpd_instance_namespace }}' namespace"
    cpd_admin_url: "{{ cpd_admin_url_output.stdout }}"
  when: cpd_admin_username_output.stdout | length > 0

# Debug Cloud Pak for Data installation details
# -----------------------------------------------------------------------------
- name: "get-cpd-details : Debug : Cloud Pak for Data {{ cpd_product_version }} details"
  debug:
    msg:
      - "CP4D Dashboard ......................... https://{{ cpd_admin_url }}"
      - "CP4D Admin Username .................... {{ cpd_admin_username }}"
      - "CP4D Admin Password .................... {{ cpd_admin_password }}"
      - "CP4D Components ........................ {{ cpd_components_list }}"
