---
# Lookup CPD credentials
# -----------------------------------------------------------------------------
# The 'ibm-iam-bindinfo-platform-auth-idp-credentials' secret will only exist if installing from CPD 4.8.x, if upgrading from 4.6.x it will continue using 'admin_user_details' secret

# Lookup CPD username in 'ibm-iam-bindinfo-platform-auth-idp-credentials' secret
# -----------------------------------------------------------------------------
- name: "get-cpd-details : Lookup Cloud Pak for Data admin username"
  shell: |
    oc get secret ibm-iam-bindinfo-platform-auth-idp-credentials -n {{ cpd_instance_namespace }} -o json | jq -r '.data.admin_username' | base64 -d
  register: cpd_admin_username_output

# Lookup CPD password
# -----------------------------------------------------------------------------
# If 'ibm-iam-bindinfo-platform-auth-idp-credentials' does not exist then it means CPD 4.8 password won't be present either
# Then, lookup in 'admin-user-details' secret which should be present if CPD 4.6 is upgraded to 4.8
- set_fact:
    cpd_admin_password_cmd: "{{ (cpd_admin_username_output.stdout | length > 0) | ternary(cpd48_admin_password_cmd, cpd46_admin_password_cmd) }}"
    cpd_admin_password_text: "{{ (cpd_admin_username_output.stdout | length > 0) | ternary(cpd48_admin_password_text, cpd46_admin_password_text) }}"
  vars:
    cpd46_admin_password_cmd: "oc get secret admin-user-details -n {{ cpd_instance_namespace }} -o json | jq -r '.data.initial_admin_password' | base64 -d"
    cpd48_admin_password_cmd: "oc get secret ibm-iam-bindinfo-platform-auth-idp-credentials -n {{ cpd_instance_namespace }} -o json | jq -r '.data.admin_password' | base64 -d"
    cpd46_admin_password_text: "Found in 'admin_user_details' secret under '{{ cpd_instance_namespace }}' namespace"
    cpd48_admin_password_text: "Found in 'ibm-iam-bindinfo-platform-auth-idp-credentials' secret under '{{ cpd_instance_namespace }}' namespace"

- name: "get-cpd-details : Lookup Cloud Pak for Data admin password"
  shell: "{{ cpd_admin_password_cmd }}"
  register: cpd_admin_password_output

# Lookup CPD URL
# -----------------------------------------------------------------------------
- name: "get-cpd-details : Lookup Cloud Pak for Data admin url"
  shell: |
    oc get ZenService lite-cr -o jsonpath="{.status.url}{'\n'}" -n {{ cpd_instance_namespace }}
  register: cpd_admin_url_output
  failed_when: cpd_admin_url_output.stdout | length == 0

# Set CPD admin username, password and url
# -----------------------------------------------------------------------------
- name: "get-cpd-details : Set Cloud Pak for Data deployment details"
  set_fact:
    cpd_admin_username: "{{ (cpd_admin_username_output.stdout | length > 0) | ternary('cpadmin','admin') }}"
    cpd_admin_password: "{{ cpd_admin_password_output.stdout }}"
    cpd_admin_url: "https://{{ cpd_admin_url_output.stdout }}"

# Debug Cloud Pak for Data installation details
# -----------------------------------------------------------------------------
- name: "get-cpd-details : Debug : Cloud Pak for Data {{ cpd_product_version }} details"
  debug:
    msg:
      - "CP4D Dashboard ......................... {{ cpd_admin_url }}"
      - "CP4D Admin Username .................... {{ cpd_admin_username }}"
      - "CP4D Admin Password .................... {{ cpd_admin_password_text }}"
      - "CP4D Components ........................ {{ cpd_components_list }}"
