---
# This task runs 'cpd-cli manage apply-cr' command which is responsible for installing CPD related custom resources

# Debug components to be installed
- name: "install-cr : Debug Cloud Pak for Data components to be installed"
  debug:
    msg:
      - "Release ......................... {{ cpd_product_version }}"
      - "Components ...................... {{ cpd_components_list }}"

# CP4D services require that some of their service accounts to have ibm-entitlement-key set imagePullPolicy
# Invoke this task with the custom resource install as service accounts might get deleted if the service is uninstalled
- name: "install-cr : Pre-create Cloud Pak for Data serviceAccounts with ibm-entitlement-key in imagePullSecret"
  kubernetes.core.k8s:
    apply: yes
    template: templates/cpd_platform/cpd-service-accounts.yml.j2
  register: cpd_sa_create
  retries: 2
  delay: 15 # seconds
  until: cpd_sa_create.error is not defined # The error field will be set to 409 if there was a conflict

# Set cpd-cli command to be executed
- name: "install-cr : Set command : Install Cloud Pak for Data custom resources : {{ cpd_components_list }}"
  set_fact:
    cpd_cmd_apply_cr: cpd-cli manage apply-cr \
      --release={{ cpd_product_version }} \
      --cpd_instance_ns={{ cpd_instance_namespace }}  \
      --components={{ cpd_components }} \
      --block_storage_class={{ cpd_metadata_storage_class }} \
      --file_storage_class={{ cpd_primary_storage_class }} \
      --parallel_num={{ cpd_components_list | length }} \
      --license_acceptance=true 2>&1 | tee {{ role_path }}/logs/cpd_components_install_cr.log

# Debug cpd-cli command to be executed
# The output can be copied/pasted in terminal in order to re-run cpd-cli command directly for troubleshooting purposes
- name: "install-cr : Debug command : Install Cloud Pak for Data custom resources : {{ cpd_components_list }}"
  debug:
    msg:
      - "{{ cpd_cmd_apply_cr | regex_replace(' \\\\', '') }}"

# Execute async cpd-cli command to install corresponding custom resources
- name: "install-cr : Running command : Install Cloud Pak for Data custom resources : {{ cpd_components_list }} (up to 360 minutes)"
  async: 21600 # 360 minutes
  poll: 0
  shell: "{{ cpd_cmd_apply_cr }}"
  register: cpd_install_cr_output

- debug:
    msg:
      - "{{ cpd_components_list | intersect(cpd_components_depending_ccs_list) | length > 0 }}"

# Follow through and wait for components to be installed
- include_tasks: "tasks/wait/main.yml"

# Wait async cpd-cli command to install corresponding custom resources
- name: "install-cr : Waiting command execution : Install Cloud Pak for Data custom resources : {{ cpd_components_list }}... (60s delay)"
  async_status:
    jid: "{{ cpd_install_cr_output.ansible_job_id }}"
  register: cpd_install_cr_async_output
  until: cpd_install_cr_async_output.finished
  retries: 360 # wait up to 6 hours
  delay: 60
  failed_when: ('apply-cr command ran successfully' not in cpd_install_cr_async_output.stdout)

# Debug cpd-cli command output
- name: "install-cr : Debug command output : Install Cloud Pak for Data custom resources : {{ cpd_components_list }}"
  debug:
    msg: "{{ cpd_install_cr_async_output.stdout }}"
