# Use the appropriate cpd-cli manage command to create or update
# the global image pull secret with the appropriate credentials
- name: "cpd-cli: Run - Configure cpd image pull secret"
  shell: |
    cpd-cli manage add-icr-cred-to-global-pull-secret \
    --entitled_registry_key={{ cpd_entitlement_key }} 2>&1 | tee {{ role_path }}/logs/cpd_platform_step2_cpd_config_image_pull_secret_output.log
  register: cpd_config_image_pull_secret_output
  failed_when: cpd_config_image_pull_secret_output.rc > 0 or ('add-icr-cred-to-global-pull-secret command ran successfully' not in cpd_config_image_pull_secret_output.stdout)

- name: "cpd-cli: Debug - Configure cpd image pull secret"
  debug:
    msg: "{{ cpd_config_image_pull_secret_output.stdout }}"

# The command:
# - Creates nss-managed-role-from-ibm-cpd-operators role
#   and rolebinding for ibm-namespace-scope-operator service account
# - Creates the specified projects if they don't already exist.
# - Creates the NamespaceScope operator in the operators project.
# - Applies the require role to the operands project and any tethered projects.
# - Binds the applied role to the service account of the NamespaceScope operator.
- name: "cpd-cli: Run Step 3/10 - Configure cpd namespaces"
  shell: |
    cpd-cli manage authorize-instance-topology \
    --cpd_operator_ns={{ cpd_operators_namespace }} \
    --cpd_instance_ns={{ cpd_instance_namespace }} 2>&1 | tee {{ role_path }}/logs/cpd_platform_step3_cpd_config_namespaces_output.log
  register: cpd_config_namespaces_output
  failed_when: cpd_config_namespaces_output.rc > 0 or ('authorize-instance-topology command ran successfully' not in cpd_config_namespaces_output.stdout)

- name: "cpd-cli: Debug Step 3/10 - Configure cpd namespaces"
  debug:
    msg: "{{ cpd_config_namespaces_output.stdout }}"

# Assign the user the role in the operators project for the instance:
- name: Create cpd service account and cluster role binding
  kubernetes.core.k8s:
    apply: yes
    template: "templates/rbac.yml.j2"

- name: "cpd-cli: Lookup logged user to grant access to cpd"
  shell: oc whoami
  register: cpd_whoami
  failed_when: cpd_whoami.stdout | length == 0

- set_fact:
    cpd_user_access: "{{ cpd_whoami.stdout }}"

# TODO: Test a way to grant logged user the access to CPD
- name: "cpd-cli: Run Step 4/10 - Assign admin user the role in the {{ cpd_operators_namespace }} operators project for cpd-instance-admin-rbac"
  shell: |
    oc adm policy add-role-to-user admin {{ cpd_user_access }} \
    --namespace={{ cpd_operators_namespace }} \
    --rolebinding-name="cpd-instance-admin-rbac" 2>&1 | tee {{ role_path }}/logs/cpd_platform_step4_cpd_assign_permission_operators_ns_output.log
  register: cpd_assign_permission_operators_ns_output
  failed_when: cpd_assign_permission_operators_ns_output.rc > 0 or ('clusterrole.rbac.authorization.k8s.io/admin added' not in cpd_assign_permission_operators_ns_output.stdout)

- name: "cpd-cli: Debug Step 4/10 - Assign admin user the role in the {{ cpd_operators_namespace }} operators project for cpd-instance-admin-rbac"
  debug:
    msg: "{{ cpd_assign_permission_operators_ns_output.stdout }}"

- name: "cpd-cli: Run Step 5/10 - Assign admin user the role in the {{ cpd_instance_namespace }} operands project for cpd-instance-admin-rbac"
  shell: |
    oc adm policy add-role-to-user admin {{ cpd_user_access }} \
    --namespace={{ cpd_instance_namespace }} \
    --rolebinding-name="cpd-instance-admin-rbac" 2>&1 | tee {{ role_path }}/logs/cpd_platform_step5_cpd_assign_permission_operands_ns_output.log
  register: cpd_assign_permission_operands_ns_output
  failed_when: cpd_assign_permission_operands_ns_output.rc > 0 or ('clusterrole.rbac.authorization.k8s.io/admin added' not in cpd_assign_permission_operands_ns_output.stdout)

- name: "cpd-cli: Debug Step 5/10 - Assign admin user the role in the {{ cpd_instance_namespace }} operands project for cpd-instance-admin-rbac"
  debug:
    msg: "{{ cpd_assign_permission_operands_ns_output.stdout }}"

- name: "cpd-cli: Run Step 6/10 - Assign cpd-instance-admin-apply-olm user the role in the {{ cpd_operators_namespace }} operators project for cpd-instance-admin-apply-olm-rbac"
  shell: |
    oc adm policy add-role-to-user cpd-instance-admin-apply-olm {{ cpd_user_access }} \
    --namespace={{ cpd_operators_namespace }} \
    --role-namespace={{ cpd_operators_namespace }}  \
    --rolebinding-name="cpd-instance-admin-apply-olm-rbac" 2>&1 | tee {{ role_path }}/logs/cpd_platform_step6_cpd_assign_permission_apply_olm_output.log
  register: cpd_assign_permission_apply_olm_output
  failed_when: cpd_assign_permission_apply_olm_output.rc > 0 or ('role.rbac.authorization.k8s.io/cpd-instance-admin-apply-olm added' not in cpd_assign_permission_apply_olm_output.stdout)

- name: "cpd-cli: Debug Step 6/10 - Assign cpd-instance-admin-apply-olm user the role in the {{ cpd_operators_namespace }} operators project for cpd-instance-admin-apply-olm-rbac"
  debug:
    msg: "{{ cpd_assign_permission_apply_olm_output.stdout }}"

# Install IBM Licensing and check where Certificate Manager is installed
- name: Detect Certificate Manager installation
  include_tasks: "{{ role_path }}/../../common_tasks/detect_cert_manager.yml"
  when: cert_manager_namespace is not defined or cert_manager_namespace | length == 0

- name: "cpd-cli: Run Step 7/10 - Install Cloud Pak for Data dependency: IBM Licensing"
  shell: |
    cpd-cli manage apply-cluster-components \
    --release={{ cpd_product_version }} \
    --license_acceptance=true \
    --skip_components=ibm-cert-manager \
    --cert_manager_ns={{ cert_manager_namespace }} \
    --licensing_ns={{ cpd_ibm_licensing_namespace }} 2>&1 | tee {{ role_path }}/logs/cpd_platform_step7_cpd_install_ibm_licensing_output.log
  register: cpd_install_ibm_licensing_output
  failed_when: cpd_install_ibm_licensing_output.rc > 0 or ('apply-cluster-components command ran successfully' not in cpd_install_ibm_licensing_output.stdout)

- name: "cpd-cli: Debug Step 7/10 - Install Cloud Pak for Data dependency: IBM Licensing"
  debug:
    msg: "{{ cpd_install_ibm_licensing_output.stdout }}"

# - Creates catalog sources: opencloud-operators and cloud-native-postgresql-catalog
# - Installs Foundational Services v4.3 (Scaling CPFS size to small), IBM Namespace Scope operator v4.2, Operand Deployment Lifecycle Manager v4.2
- name: "cpd-cli: Run Step 8/10 - Install Cloud Pak for Data dependency: Foundational Services"
  shell: |
    cpd-cli manage setup-instance-topology \
    --release={{ cpd_product_version }} \
    --cpd_operator_ns={{ cpd_operators_namespace }} \
    --cpd_instance_ns={{ cpd_instance_namespace }}  \
    --license_acceptance=true \
    --block_storage_class={{ cpd_metadata_storage_class }} 2>&1 | tee {{ role_path }}/logs/cpd_platform_step8_cpd_install_cpfs_output.log
  register: cpd_install_cpfs_output
  failed_when: cpd_install_cpfs_output.rc > 0 or ('setup-instance-topology command ran successfully' not in cpd_install_cpfs_output.stdout)

- name: "cpd-cli: Debug Step 8/10 - Install Cloud Pak for Data dependency: Foundational Services"
  debug:
    msg: "{{ cpd_install_cpfs_output.stdout }}"
