masbr_action: "{{ lookup('env', 'MASBR_ACTION') }}"

mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"
mas_app_id: "{{ lookup('env', 'MAS_APP_ID') }}"
