---
# Mirrors the saml-operator for dev purposes
# This playbook aligns with the ibm.mas_devops.oneclick_add_assist playbook

- name: Mirror Saml Operator Playbook
  hosts: localhost
  any_errors_fatal: true

  vars:
    mirror_mode: "{{ lookup('env', 'MIRROR_MODE') | default ('direct', True) }}"
    mirror_saml: "{{ lookup('env', 'MIRROR_SAML') | default ('True', True) | bool }}"
    saml_version: "{{ lookup('env', 'SAML_VERSION') | default ('1.0.3', True) }}"

  pre_tasks:
    # Note that REGISTRY_USERNAME and REGISTRY_PASSWORD are not required.
    # They are only needed if you have set up authentication on your private registry
    - name: Check for required environment variables
      ansible.builtin.assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
          - lookup('env', 'REGISTRY_PUBLIC_PORT') != ""
          - lookup('env', 'IBM_ENTITLEMENT_KEY') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    # # 1. Saml Operator
    # # -------------------------------------------------------------------------
    - name: ibm.mas_devops.mirror_extras_prepare
      when:
        - mirror_saml
        - mirror_mode != "from-filesystem"
      vars:
        extras_name: saml
        extras_version: "{{ saml_version }}"

    - name: ibm.mas_devops.mirror_images
      when: mirror_saml
      vars:
        manifest_name: extras_saml
        manifest_version: "{{ saml_version }}"
