---
# Add AiBroker application
#

- hosts: localhost
  any_errors_fatal: true

  vars:
    # Application Installation
    mas_app_id: aibroker
    mas_app_channel: "{{ lookup('env', 'MAS_APP_CHANNEL') | default('1.0.x', true) }}"

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'IBM_ENTITLEMENT_KEY') != ""
          - lookup('env', 'MAS_INSTANCE_ID') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    # - ibm.mas_devops.aibroker
    # - ibm.mas_devops.kmodels
    # - ibm.mas_devops.odh
    # - ibm.mas_devops.setupscript
    - ibm.mas_devops.suite_app_install
    - ibm.mas_devops.suite_app_config