---
# Set common backup job variables
# -----------------------------------------------------------------------------
- name: "Set fact: common backup job variables"
  set_fact:
    masbr_job_component:
      name: "mongodb"
      namespace: "{{ mongodb_namespace }}"
    masbr_job_data_list:
      - seq: "1"
        type: "database"


# Before run tasks
# -------------------------------------------------------------------------
- name: "Before run tasks"
  include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/before_run_tasks.yml"
  vars:
    _job_type: "backup"
    _component_info_task_path: "{{ role_path }}/tasks/providers/{{ mongodb_provider }}/get-mongo-info.yml"


# Create k8s Job to run backup tasks
# -----------------------------------------------------------------------------
- name: "Create k8s Job to run backup tasks"
  when: masbr_create_task_job
  include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/create_run_task_job.yml"
  vars:
    _rt_role_env:
      - name: "ROLE_NAME"
        value: "mongodb"
      - name: "MONGODB_PROVIDER"
        value: "{{ mongodb_provider }}"
      - name: "MONGODB_ACTION"
        value: "{{ mongodb_action }}"


- name: "Run backup tasks"
  when: not masbr_create_task_job
  block:
    # Update backup job status: New
    # -------------------------------------------------------------------------
    - name: "Update backup job status: New"
      include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/update_job_status.yml"
      vars:
        _job_data_list:
          - seq: "1"
            phase: "New"


    # Run backup tasks for each data type
    # -------------------------------------------------------------------------
    - name: "Run backup tasks for each data type"
      include_tasks: "tasks/providers/{{ mongodb_provider }}/backup-{{ job_data_item.type }}.yml"
      vars:
        masbr_job_data_seq: "{{ job_data_item.seq }}"
        masbr_job_data_type: "{{ job_data_item.type }}"
      loop: "{{ masbr_job_data_list }}"
      loop_control:
        loop_var: job_data_item

  rescue:
    # Update backup status: Failed
    # -------------------------------------------------------------------------
    - name: "Update database backup status: Failed"
      include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/update_job_status.yml"
      vars:
        _job_status:
          phase: "Failed"

  always:
    # After run tasks
    # -------------------------------------------------------------------------
    - name: "After run tasks"
      include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/after_run_tasks.yml"
