---
# Copy backup file from specified storage location to pod
# -------------------------------------------------------------------------
- name: "Copy backup file from specified storage location to pod"
  include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/copy_storage_files_to_pod.yml"
  vars:
    masbr_cf_job_type: "backup"
    masbr_cf_job_name: "{{ _job_completed_name }}"
    masbr_cf_paths:
      - src_file: "{{ masbr_job_data_type }}/{{ _job_name }}.tar.gz"
        dest_folder: "{{ mongodb_restore_folder }}"


# Extract the tar.gz file
# -------------------------------------------------------------------------
- name: "Extract the tar.gz file"
  changed_when: true
  shell: >
    {{ exec_in_pod_begin }}
    mkdir -p {{ mongodb_restore_folder }}/{{ _job_name }} &&
    tar -xzf {{ mongodb_restore_folder }}/{{ _job_name }}.tar.gz
    -C {{ mongodb_restore_folder }}/{{ _job_name }} . &&
    ls -lA {{ mongodb_restore_folder }}/{{ _job_name }}
    {{ exec_in_pod_end }}
  register: _extract_output

- name: "Debug: list extracted files"
  debug:
    msg:
      - "Extract output folder .............. {{ mongodb_restore_folder }}/{{ _job_name }}"
      - "{{ _extract_output.stdout_lines }}"


# Restore mongodb databases
# -------------------------------------------------------------------------
- name: "Restore mongodb databases"
  changed_when: true
  shell: >
    {{ exec_in_pod_begin }}
    mongorestore --host={{ mongodb_primary_host }}
    --username={{ mongodb_user }} --password={{ mongodb_password }}
    --authenticationDatabase=admin --ssl --sslCAFile={{ mongodb_ca_file }}
    --drop --oplogReplay --dir={{ mongodb_restore_folder }}/{{ _job_name }}
    |& tee -a {{ mongodb_restore_log }}
    {{ exec_in_pod_end }}
  register: _mongorestore_output

- name: "Debug: mongorestore output"
  debug:
    msg: "{{ _mongorestore_output.stdout_lines }}"
