---
# Update database restore status: InProgress
# -----------------------------------------------------------------------------
- name: "Update database restore status: InProgress"
  include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/update_job_status.yml"
  vars:
    _job_component:
      version: "{{ mongodb_version }}"
      provider: "{{ mongodb_provider }}"
    _job_data_list:
      - seq: "{{ masbr_job_data_seq }}"
        phase: "InProgress"


- name: "Restore mongodb databases"
  block:
    # Create mongodb role and user for backing up databases
    # -------------------------------------------------------------------------
    - name: "Create mongodb role and user for backing up databases"
      include_tasks: "tasks/providers/{{ mongodb_provider }}/create-role-user.yml"


    # Prepare mongodb database restore folders
    # -------------------------------------------------------------------------
    - name: "Set fact: mongodb database restore variables"
      set_fact:
        mongodb_restore_folder: >-
          {{ masbr_pod_temp_folder }}/{{ masbr_job_name }}/{{ masbr_job_data_type }}

    - name: "Set fact: mongodb database restore log"
      set_fact:
        mongodb_restore_log: "{{ mongodb_restore_folder }}/mongodb-restore.log"

    - name: "Create mongodb database restore folder in pod"
      changed_when: true
      shell: >
        {{ exec_in_pod_begin }}
        mkdir -p {{ mongodb_restore_folder }};
        chmod a+w {{ mongodb_restore_folder }}
        {{ exec_in_pod_end }}

    - name: "Debug: mongodb database restore folder in pod"
      debug:
        msg: "Database restore folder ........... {{ mongodb_restore_folder }}"


    # This is an incremental backup, need to restore ancestor full backup first
    # -------------------------------------------------------------------------
    - name: "Restore ancestor full backup"
      when: masbr_restore_from_incr
      block:
        - name: "Copy ancestor full backup file from specified storage location to pod"
          include_tasks: "{{ role_path }}/tasks/providers/{{ mongodb_provider }}/copy-restore-mongo-backup-file.yml"
          vars:
            _job_name: "{{ masbr_restore_ancestor }}"
            _job_completed_name: "{{ masbr_restore_ancestor_completed }}"


    # Restore the specified Full or Incremental backup
    # -------------------------------------------------------------------------
    - name: "Copy backup file from specified storage location to pod"
      include_tasks: "{{ role_path }}/tasks/providers/{{ mongodb_provider }}/copy-restore-mongo-backup-file.yml"
      vars:
        _job_name: "{{ masbr_restore_from }}"
        _job_completed_name: "{{ masbr_restore_from_completed }}"


    # Copy mongodb restore log file from pod to specified storage location
    # -------------------------------------------------------------------------
    - name: "Create a tar.gz archive of mongodb restore log"
      changed_when: true
      shell: >
        {{ exec_in_pod_begin }}
        tar -czf {{ mongodb_restore_folder }}/mongodb-restore-log.tar.gz
        -C {{ mongodb_restore_folder }} mongodb-restore.log
        {{ exec_in_pod_end }}

    - name: "Copy mongodb restore log file from pod to specified storage location"
      include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/copy_pod_files_to_storage.yml"
      vars:
        masbr_cf_job_type: "{{ masbr_job_type }}"
        masbr_cf_job_name: "{{ masbr_job_name }}"
        masbr_cf_paths:
          - src_file: "{{ mongodb_restore_folder }}/mongodb-restore-log.tar.gz"
            dest_folder: "log"


    # Update database restore status: Completed
    # -------------------------------------------------------------------------
    - name: "Update database restore status: Completed"
      include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/update_job_status.yml"
      vars:
        _job_data_list:
          - seq: "{{ masbr_job_data_seq }}"
            phase: "Completed"

  rescue:
    # Update database restore status: Failed
    # -------------------------------------------------------------------------
    - name: "Update database restore status: Failed"
      include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/update_job_status.yml"
      vars:
        _job_data_list:
          - seq: "{{ masbr_job_data_seq }}"
            phase: "Failed"

  always:
    # Clean up
    - name: "Delete database restore files from mongodb pod"
      changed_when: true
      shell: >
        {{ exec_in_pod_begin }}
        rm -rf {{ mongodb_restore_folder }}
        {{ exec_in_pod_end }}
      register: _delete_pod_files_output
