---
- name: "Install controller configmap"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/kmodels-controller/configmap.yml.j2') }}"

- name: "Install controller deployment"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/kmodels-controller/deployment.yml.j2') }}"

- name: "Install controller network"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/kmodels-controller/network.yml.j2') }}"

- name: "Install controller pvc"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/kmodels-controller/pvc.yml.j2') }}"

- name: "Install controller rbac"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/kmodels-controller/rbac.yml.j2') }}"
