---
# About this task:
# Several IBM Cloud Pak for Data services require Multicloud Object Gateway.
# If you plan to install watsonx Assistant, Watson™ Discovery, or Watson Speech services
# you might need to install and configure Multicloud Object Gateway.

# Use the setup-mcg command to create secrets for one or more of the following services:

# watsonx Assistant
# Watson Discovery
# Watson Speech services
# The secrets enable the services to access the following secrets in the openshift-storage project:

# The secret that contains the NooBaa account credentials.
# The secret that contains the NooBaa account certificate.

# More details: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=piicpd-creating-secrets-services-that-use-multicloud-object-gateway

#  Configure pre-requisites for Watson Discovery
# ---------------------------------------------------------------------------------------------------

# Set cpd-cli command to be executed
- name: "prereqs : watson_discovery : Set command : Watson Discovery pre-reqs : Create secrets for services that use Multicloud Object Gateway"
  set_fact:
    cpd_cmd_setup_mcg: cpd-cli manage setup-mcg \
      --components=watson_discovery \
      --cpd_instance_ns={{ cpd_instance_namespace }} \
      --noobaa_ns=openshift-storage \
      --noobaa_account_secret=noobaa-admin \
      --noobaa_cert_secret=noobaa-s3-serving-cert 2>&1 | tee {{ cpd_logs_dir }}/cpd_service_prereq_watson_discovery_output.log

# Debug cpd-cli command to be executed
# The output can be copied/pasted in terminal in order to re-run cpd-cli command directly for troubleshooting purposes
- name: "prereqs : watson_discovery : Debug command : Watson Discovery pre-reqs : Create secrets for services that use Multicloud Object Gateway"
  debug:
    msg:
      - "{{ cpd_cmd_setup_mcg | regex_replace(' \\\\', '') }}"

# Execute cpd-cli command to configure Watson Discovery dependencies
- name: "prereqs : watson_discovery : Running command : Watson Discovery pre-reqs : Create secrets for services that use Multicloud Object Gateway"
  shell: "{{ cpd_cmd_setup_mcg }}"
  register: cpd_config_wd_prereqs_output
  failed_when: ('setup-mcg command ran successfully' not in cpd_config_wd_prereqs_output.stdout)

# Debug cpd-cli command output
- name: "prereqs : watson_discovery : Debug command output : Watson Discovery pre-reqs : Create secrets for services that use Multicloud Object Gateway"
  debug:
    msg: "{{ cpd_config_wd_prereqs_output.stdout }}"
