kind: Deployment
apiVersion: apps/v1
metadata:
  name: istio-operator
  namespace: openshift-operators
  labels:
    olm.deployment-spec-hash: 6fccff884c
    olm.owner: servicemeshoperator.v2.5.1
    olm.owner.kind: ClusterServiceVersion
    olm.owner.namespace: openshift-operators
    operators.coreos.com/servicemeshoperator.openshift-operators: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: istio-operator
      annotations:
        olm.relatedImage.v2_3.cni: >-
          registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:d7576d94c50a1f18d5162d45ba9a628303211f64862c1507ad6d15e6bb830c01
        olm.skipRange: '>=1.0.2 <2.5.1-0'
        olm.relatedImage.v2_4.cni: >-
          registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:8e36644dc0f6fe5018b6643cca057ded23aa9b8a026280b864f5f1cc1fa0f259
        oauth-proxy.name: oauth-proxy
        features.operators.openshift.io/token-auth-azure: 'false'
        operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift Platform Plus"]'
        olm.relatedImage.v2_5.cni: >-
          registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:205a39b2b48bff0d705c1879da7a2969c201eb319d38b2235ac1caff5bed4360
        oauth-proxy.tag: v4.4
        olm.relatedImage.v2_2.grafana: >-
          registry.redhat.io/openshift-service-mesh/grafana-rhel8@sha256:dff9810ee591b51ac25b93c9cd132d61771fa85888496f84a0da3d9d22831a79
        oauth-proxy.namespace: openshift
        features.operators.openshift.io/token-auth-gcp: 'false'
        olm.relatedImage.v2_5.prometheus: >-
          registry.redhat.io/openshift4/ose-prometheus@sha256:f5654f60b945c6faa2f9d97e048521ae272434aad395db45f2b2f14dc5cece0f
        olm.relatedImage.v2_3.grafana: >-
          registry.redhat.io/openshift-service-mesh/grafana-rhel8@sha256:9e30441691add3e43b9034b92fbc3163c2d03230503ced4a169cfe2ff9ad6d5c
        olm.relatedImage.v2_4.prometheus: >-
          registry.redhat.io/openshift4/ose-prometheus@sha256:f5654f60b945c6faa2f9d97e048521ae272434aad395db45f2b2f14dc5cece0f
        certified: 'false'
        olm.relatedImage.v2_4.grafana: >-
          registry.redhat.io/openshift-service-mesh/grafana-rhel8@sha256:2474d99af3378c05b26d298cd048895f87d78f6f7627f8f0b391eed299d1b649
        olm.targetNamespaces: ''
        operatorframework.io/properties: >-
          {"properties":[{"type":"olm.gvk","value":{"group":"maistra.io","kind":"ServiceMeshControlPlane","version":"v1"}},{"type":"olm.gvk","value":{"group":"maistra.io","kind":"ServiceMeshControlPlane","version":"v2"}},{"type":"olm.gvk","value":{"group":"maistra.io","kind":"ServiceMeshMember","version":"v1"}},{"type":"olm.gvk","value":{"group":"maistra.io","kind":"ServiceMeshMemberRoll","version":"v1"}},{"type":"olm.package","value":{"packageName":"servicemeshoperator","version":"2.5.1-0"}}]}
        olm.relatedImage.v2_5.grafana: >-
          registry.redhat.io/openshift-service-mesh/grafana-rhel8@sha256:b2576fb445714ff8cd38f08967e7ff2af2b7431300be5281f73e5918fbb8acbb
        olm.relatedImage.v2_3.prometheus: >-
          registry.redhat.io/openshift-service-mesh/prometheus-rhel8@sha256:b7b9c1481e6a7f59ac31952b11eb01ee0f27047acd13dc673dc969341992bbb6
        olm.relatedImage.v2_2.prometheus: >-
          registry.redhat.io/openshift-service-mesh/prometheus-rhel8@sha256:02440db7428767eb5f4596219b633af0d015edb2b8e5ec85b147dcf8b6cff739
        olm.relatedImage.v2_5.prometheus-config-reloader: >-
          registry.redhat.io/openshift4/ose-prometheus-config-reloader@sha256:c0e4bf1a74d5db4dda67d02a4a7069e898d6a6bf91862846ab96c83b84695fa6
        repository: 'https://github.com/maistra/istio-operator'
        olm.relatedImage.v2_2.proxyv2: >-
          registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:f12ac415a61985b7c8b1b1afa91dd52d35defbdbd8facbe5d35d423c62ca1575
        olm.relatedImage.v2_4.prometheus-config-reloader: >-
          registry.redhat.io/openshift4/ose-prometheus-config-reloader@sha256:c0e4bf1a74d5db4dda67d02a4a7069e898d6a6bf91862846ab96c83b84695fa6
        olm.relatedImage.v2_3.proxyv2: >-
          registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:891cac1c03beb2ec60981ed0001add85f0084cda538562e0accc48893494de85
        olm.relatedImage.v2_4.proxyv2: >-
          registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:186619a888331a58729e27e67fbcee236875c1998b6714565238db53e9a1f8bd
        olm.relatedImage.v2_5.proxyv2: >-
          registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:7c413c4ec671f301ea71b6ad59d4673929f2d110e4e427beeb487c74b393e083
        features.operators.openshift.io/token-auth-aws: 'false'
        support: 'Red Hat, Inc.'
        oauth-proxy.query: 'true'
        operators.openshift.io/infrastructure-features: '["Disconnected","fips"]'
        alm-examples: |-
          [
            {
              "apiVersion": "maistra.io/v2",
              "kind": "ServiceMeshControlPlane",
              "metadata": {
                "name": "basic",
                "namespace": "control-plane-namespace"
              },
              "spec": {
                "version": "v2.5",
                "tracing": {
                  "type": "Jaeger",
                  "sampling": 10000
                },
                "policy": {
                   "type": "Istiod"
                },
                "telemetry": {
                   "type": "Istiod"
                },
                "addons": {
                  "jaeger": {
                    "install": {
                      "storage": {
                        "type": "Memory"
                      }
                    }
                  },
                  "prometheus": {
                    "enabled": true
                  },
                  "kiali": {
                    "enabled": true
                  },
                  "grafana": {
                    "enabled": true
                  }
                }
              }
            },
            {
              "apiVersion": "maistra.io/v1",
              "kind": "ServiceMeshMemberRoll",
              "metadata": {
                "name": "default",
                "namespace": "control-plane-namespace"
              },
              "spec": {
                "members": [
                  "your-project",
                  "another-of-your-projects"
                ]
              }
            },
            {
              "apiVersion": "maistra.io/v1",
              "kind": "ServiceMeshMember",
              "metadata": {
                "name": "default",
                "namespace": "application-namespace"
              },
              "spec": {
                "controlPlaneRef": {
                  "name": "basic",
                  "namespace": "control-plane-namespace"
                }
              }
            }
          ]
        capabilities: Seamless Upgrades
        features.operators.openshift.io/csi: 'false'
        features.operators.openshift.io/fips-compliant: 'true'
        features.operators.openshift.io/cnf: 'false'
        olm.operatorNamespace: openshift-operators
        olm.relatedImage.v2_2.pilot: >-
          registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:2f141d3f9386d341addb9fc5aa91a39419af30cb0b53934b89e462aa73ca6143
        olm.relatedImage.v2_2.rls: >-
          registry.redhat.io/openshift-service-mesh/ratelimit-rhel8@sha256:c098892b78720699a5465696c337dcc887d0aa0de35bfd8f0c03e7e8df6d5379
        containerImage: >-
          registry.redhat.io/openshift-service-mesh/istio-rhel8-operator@sha256:d256a729a61e11dbba4d724612b23d4e5662dbb01f1567dec9fa13adab6287a5
        olm.relatedImage.v2_3.pilot: >-
          registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:a46c6e3553f38f3ef1ffec6e5f774e7038066ce7db11dc31cdf74bbee25baf6c
        olm.relatedImage.v2_2.wasm-cacher: >-
          registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:2f141d3f9386d341addb9fc5aa91a39419af30cb0b53934b89e462aa73ca6143
        olm.relatedImage.v2_4.pilot: >-
          registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:1a8882f482044b38e6d75e322db6d6b80d21525f56fdd08f7f2ee9a58897e742
        olm.relatedImage.v2_3.rls: >-
          registry.redhat.io/openshift-service-mesh/ratelimit-rhel8@sha256:666bfe25e4583efa71fa14e587365e63ba9baeb4359f691eb731725a4ad1b5a8
        createdAt: '2024-03-18T18:51:19CET'
        olm.relatedImage.v2_3.wasm-cacher: >-
          registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:a46c6e3553f38f3ef1ffec6e5f774e7038066ce7db11dc31cdf74bbee25baf6c
        features.operators.openshift.io/cni: 'true'
        olm.relatedImage.v2_4.rls: >-
          registry.redhat.io/openshift-service-mesh/ratelimit-rhel8@sha256:69232a0efae0517a33513582c8b088f6142314316a202b46de869df448494454
        categories: 'OpenShift Optional, Integration & Delivery'
        features.operators.openshift.io/proxy-aware: 'true'
        description: >-
          The OpenShift Service Mesh Operator enables you to install, configure,
          and manage an instance of Red Hat OpenShift Service Mesh. OpenShift
          Service Mesh is based on the open source Istio project.
        olm.relatedImage.v2_5.pilot: >-
          registry.redhat.io/openshift-service-mesh/pilot-rhel8@sha256:f12207461e6613649d6c62eea7bdf00829715249068796d59ba2fe99c19948ae
        olm.operatorGroup: global-operators
        olm.relatedImage.v2_5.rls: >-
          registry.redhat.io/openshift-service-mesh/ratelimit-rhel8@sha256:89d092eb5d4a0452a6830d14e4972e33235e83ca8bc14ecacf47d7391bab3b8a
        features.operators.openshift.io/disconnected: 'true'
        olm.relatedImage.v2_2.cni: >-
          registry.redhat.io/openshift-service-mesh/istio-cni-rhel8@sha256:377c52c8907845335cd861ab73ae54a5e28399514254de8a1361f36f59d9387b
        features.operators.openshift.io/tls-profiles: 'false'
    spec:
      restartPolicy: Always
      serviceAccountName: istio-operator
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /readyz
              port: 11200
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: istio-operator
          command:
            - istio-operator
            - '--config'
            - /etc/operator/olm/config.properties
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: istio-operator
            - name: OPERATOR_CONDITION_NAME
              value: servicemeshoperator.v2.5.1
          ports:
            - name: validation
              containerPort: 11999
              protocol: TCP
            - name: probes
              containerPort: 11200
              protocol: TCP
            - name: metrics
              containerPort: 60000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: operator-olm-config
              readOnly: true
              mountPath: /etc/operator/olm
            - name: webhook-tls-volume
              readOnly: true
              mountPath: /tmp/k8s-webhook-server/serving-certs
            - name: smcp-templates
              readOnly: true
              mountPath: /usr/local/share/istio-operator/templates/
          terminationMessagePolicy: File
          image: >-
            registry.redhat.io/openshift-service-mesh/istio-rhel8-operator@sha256:d256a729a61e11dbba4d724612b23d4e5662dbb01f1567dec9fa13adab6287a5
      serviceAccount: istio-operator
      volumes:
        - name: operator-olm-config
          downwardAPI:
            items:
              - path: config.properties
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
            defaultMode: 420
        - name: webhook-tls-volume
          secret:
            secretName: maistra-operator-serving-cert
            defaultMode: 420
            optional: true
        - name: smcp-templates
          configMap:
            name: smcp-templates
            defaultMode: 420
            optional: true
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
status:
  observedGeneration: 361
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2024-04-25T10:24:13Z'
      lastTransitionTime: '2024-02-28T14:16:49Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "istio-operator-55c77f9997" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2024-05-08T23:01:14Z'
      lastTransitionTime: '2024-05-08T23:01:14Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
