---
- name: Load variables (main)
  include_vars: "vars/main.yml"

- include_tasks: tasks/aibroker/main.yml

- include_tasks: tasks/tenant/main.yml

- include_tasks: tasks/apikey/main.yml

- include_tasks: tasks/s3/main.yml

- include_tasks: tasks/watsonx/main.yml
