---
# aibroker vars
aibroker_namespace: "mas-{{ mas_instance_id }}-aibroker"
mas_catalog_source: "{{ lookup('env', 'MAS_CATALOG_SOURCE') | default('ibm-operator-catalog', true) }}"
aibroker_channel: "{{ lookup('env', 'AIBROKER_CHANNEL') }}"
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"

# Create Api Key vars
#action: "{{ lookup('env', 'ACTION') | default('create_apikey', true) }}"
tenantName: "{{ lookup('env', 'TENANT_NAME') | default('user', true) }}"
tenantNamespace: "aibroker-{{ tenantName }}"
appDomain: "{{ lookup('env', 'APP_DOMAIN') }}"

# Main variables
ibm_entitlement_username: "{{ lookup('env','IBM_ENTITLEMENT_USERNAME') }}"
ibm_entitlement_key: "{{ lookup('env', 'IBM_ENTITLEMENT_KEY') }}"

# Source container registry
# -----------------------------------------------------------------------------
mas_icr_cp: "{{ lookup('env', 'MAS_ICR_CP') | default('cp.icr.io/cp', true) }}"
mas_icr_cpopen: "{{ lookup('env', 'MAS_ICR_CPOPEN') | default('icr.io/cpopen', true) }}"

# WatsonX
watsonxai_apikey: "{{ lookup('env', 'WATSONXAI_APIKEY') }}"
watsonxai_url: "{{ lookup('env', 'WATSONXAI_URL') }}"
watsonxai_project_id: "{{ lookup('env', 'WATSONXAI_PROJECT_ID') }}"