---
# Default application spec for Predict
mas_appws_spec:
  bindings:
    jdbc: "{{ mas_appws_bindings_jdbc | default( 'system' , true) }}"
    watsonstudio: system
  settings:
    mat:
      mat_customization_list: "{{ mat_app_settings_customization_list if (cpd_wos_datamart_id is defined and cpd_wos_datamart_id | length > 0) else [] }}"
      # datamartid: "{{ cpd_wos_datamart_id }}"
      # install: true
    watsonstudio:
      projectid: "{{ cpd_wsl_project_id }}"
    wml:
      instance_id: "{{ cpd_wml_instance_id }}"
      url: "{{ cpd_wml_url }}"
      version: "{{ cpd_product_version.split('.')[0] }}.{{ cpd_product_version.split('.')[1] }}"
    deployment:
      size: "{{ mas_appws_settings_deployment_size }}"
