---

# What cluster types does this role support
supported_cluster_types:
  - roks
  - quickburn
  - product_group
# Defaults for ROKS deployment
roks_zone: lon02
roks_flavor: "b3c.16x64"
roks_workers: "3"
roks_flags: ""

