---
# ------ CPD login ----------------------------------------------------------------------------------------------
# Option 1 - Use ocp_server and ocp_token:
# For already provisioned clusters set token and server to log directly into rather than cluster type (ROKS/Fyre) specific login
ocp_token: "{{ lookup('env', 'OCP_TOKEN') }}"
ocp_server: "{{ lookup('env', 'OCP_SERVER') }}"
cpd_admin_login_sa: "mas-cpd-cluster-admin-sa"

# Option 2: (ROKS only) Use 'ibmcloud oc cluster config' command to lookup kubeconfig for the target cluster to set the context in '{{ cpd_work_dir }}/.olm-utils/.kubeconfig' directly
cpd_work_dir: "{{ lookup('env', 'CPD_WORK_DIR') }}" # full path of your 'cpd-cli-workspace/olm-utils-workspace/work' directory i.e '$HOME/cpd-cli-workspace/olm-utils-workspace/work';

# ------ CPD install flag options ----------------------------------------------------------------------------------------------
install_cpd_platform: "{{ lookup('env', 'INSTALL_CPD_PLATFORM') | default('true', true) | bool }}" # if true will install cpd platform first, if false cpd platform install will be skipped
# cpd_upgrade_flag: "{{ lookup('env', 'CPD_UPGRADE_FLAG') | default('false', true) | bool }}" # if true, then we'll perform cpd upgrade

# ------ CPD storage classes ------------------------------------------------------------------------------------------
cpd_primary_storage_class: "{{ lookup('env', 'CPD_PRIMARY_STORAGE_CLASS') }}"
cpd_metadata_storage_class: "{{ lookup('env', 'CPD_METADATA_STORAGE_CLASS') }}"
cpd_scale_config: "{{ lookup('env', 'CPD_SCALE_CONFIG') | default('medium', true) }}"

# ------ CPD entitlement ----------------------------------------------------------------------------------------------
cpd_entitlement_username: "{{ lookup('env', 'CPD_ENTITLEMENT_USERNAME') | default('cp', true) }}"
ibm_entitlement_key: "{{ lookup('env', 'IBM_ENTITLEMENT_KEY') }}"
cpd_entitlement_key: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') | default(ibm_entitlement_key, true) }}"

# ------ CPD config parameters -----------------------------------------------------------------------------------------------
cpd_operators_namespace: "{{ lookup('env', 'CPD_OPERATORS_NAMESPACE') | default('ibm-cpd-operators', true) }}"
cpd_instance_namespace: "{{ lookup('env', 'CPD_INSTANCE_NAMESPACE') | default('ibm-cpd', true) }}"
cpd_product_version: "{{ lookup('env', 'CPD_PRODUCT_VERSION') }}"
cpd_supported_versions: ["4.8.0", "4.8.1"]
cpd_ibm_licensing_namespace: ibm-licensing

# ------ CPD component -----------------------------------------------------------------------------------------------
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-installing-cloud-pak
cpd_components: "{{ lookup('env', 'CPD_COMPONENTS') | default('cpd_platform', true) | lower }}" # minimum that must be installed to have cpd running is 'cpd_platform'
cpd_components_list: "{{ cpd_components | split(',') | sort }}" # this will parse the 'cpd_components' string into a list to be used internally in the role

# List of CPD components/services that can be installed through this role
cpd_components_supported_list:
  - cpd_platform
  - analyticsengine
  - cognos_analytics
  - openscale
  - spss
  - watson_discovery
  - ws
  - wml
  - ccs

# List of CPD services that depend on CCS to be installed
cpd_components_depending_ccs_list:
  - cognos_analytics
  - ws
  - wml
  - spss
