---
# ------ CPD login ----------------------------------------------------------------------------------------------
# Option 1 - Use ocp_server and ocp_token:
# For already provisioned clusters set token and server to log directly into rather than cluster type (ROKS/Fyre) specific login
ocp_token: "{{ lookup('env', 'OCP_TOKEN') }}"
ocp_server: "{{ lookup('env', 'OCP_SERVER') }}"
cpd_admin_login_sa: "mas-cpd-cluster-admin-sa"

# ------ CPD install flag options ----------------------------------------------------------------------------------------------
cpd_action: "{{ lookup('env', 'CPD_ACTION') | default('install', true) }}"
cpd_upgrade_flag: "{{ (cpd_action == 'upgrade') | ternary(true, false) }}"
skip_cpd_prereqs: "{{ lookup('env', 'SKIP_CPD_PREREQS') | default('false', true) | bool }}"
skip_cpd_operators: "{{ lookup('env', 'SKIP_CPD_OPERATORS') | default('false', true) | bool }}"
skip_cpd_operands: "{{ lookup('env', 'SKIP_CPD_OPERANDS') | default('false', true) | bool }}"

    record_name: "{{ (cloudflare_subdomain == '') | ternary(record_name_without_subdomain, record_name_with_subdomain) }}"


# ------ CPD storage classes ------------------------------------------------------------------------------------------
cpd_primary_storage_class: "{{ lookup('env', 'CPD_PRIMARY_STORAGE_CLASS') }}"
cpd_metadata_storage_class: "{{ lookup('env', 'CPD_METADATA_STORAGE_CLASS') }}"
cpd_scale_config: "{{ lookup('env', 'CPD_SCALE_CONFIG') | default('medium', true) }}"

# ------ CPD entitlement ----------------------------------------------------------------------------------------------
cpd_entitlement_username: "{{ lookup('env', 'CPD_ENTITLEMENT_USERNAME') | default('cp', true) }}"
ibm_entitlement_key: "{{ lookup('env', 'IBM_ENTITLEMENT_KEY') }}"
cpd_entitlement_key: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') | default(ibm_entitlement_key, true) }}"

# ------ CPD config parameters -----------------------------------------------------------------------------------------------
cpd_operators_namespace: "{{ lookup('env', 'CPD_OPERATORS_NAMESPACE') | default('ibm-cpd-operators', true) }}"
cpd_instance_namespace: "{{ lookup('env', 'CPD_INSTANCE_NAMESPACE') | default('ibm-cpd', true) }}"
cpd_cs_control_namespace: cs-control
cpd_cpfs_namespace: ibm-common-services

cpd_product_version: "{{ lookup('env', 'CPD_PRODUCT_VERSION') }}"
cpd_supported_versions: ["4.8.0", "4.8.1"]
cpd_ibm_licensing_namespace: ibm-licensing

# ------ CPD component -----------------------------------------------------------------------------------------------
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-installing-cloud-pak
cpd_components: "{{ lookup('env', 'CPD_COMPONENTS') | default('cpd_platform', true) | lower }}" # minimum that must be installed to have cpd running is 'cpd_platform'
cpd_components_list: "{{ cpd_components | split(',') | sort }}" # this will parse the 'cpd_components' string into a list to be used internally in the role

# List of CPD components/services that can be installed through this role
cpd_components_supported_list:
  - cpd_platform
  - analyticsengine
  - cognos_analytics
  - openscale
  - spss
  - watson_discovery
  - ws
  - wml
  - ccs

# List of CPD services that depend on CCS to be installed
cpd_components_depending_ccs_list:
  - cognos_analytics
  - ws
  - wml
  - spss
