---
# Openshift Serverless vars
openshift_namespace: openshift-operators
serverless_namespace: openshift-serverless
serverless_catalog_source: "{{ lookup('env', 'SERVERLESS_CATALOG_SOURCE') | default('redhat-operators', true) }}"
serverless_channel: "{{ lookup('env', 'SERVERLESS_CHANNEL') | default('stable', true) }}"

# Openshift Service Mesh vars
serviceMeshNamespace: openshift-operators

# Authorino operator vars
authorino_catalog_source: "{{ lookup('env', 'AUTHORINO_CATALOG_SOURCE') | default('community-operators', true) }}"

# ODH operator vars
odh_channel: "{{ lookup('env', 'ODH_CHANNEL') | default('fast', true) }}"
odh_catalog_source: "{{ lookup('env', 'AUTHORINO_CATALOG_SOURCE') | default('community-operators', true) }}"