---
- hosts: localhost
  vars:
    type: dev
    workers:
      number: 3
      cpu: 16
      memory: 64
    masters:
      number: 3
      cpu: 4
      memory: 8
  roles:
    - mas.devops.ocp_provision
