---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # Required to setup the cluster
    # -------------------------------------------------------------------------
    cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
    cluster_type: product_group
    username: "{{ lookup('env', 'FYRE_USERNAME') }}"
    password: "{{ lookup('env', 'FYRE_APIKEY') }}"
    ocp_version: "{{ lookup('env', 'OCP_VERSION') }}"
    workers_count: "{{ lookup('env', 'WORKER_COUNT') | default('6', true) }}"
    fyre_product_id: "{{ lookup('env', 'FYRE_PRODUCT_ID') }}"


    # Required to install CP4D
    # -------------------------------------------------------------------------
    cpd_registry: cp.icr.io
    cpd_registry_user: cp
    cpd_registry_password: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') }}"
    cpd_meta_namespace: cpd-meta-ops
    cpd_storage_class: ocs-storagecluster-cephfs

    # Required to install Db2 (there are defaults built into the role as well)
    # -------------------------------------------------------------------------
    db2wh_version: 11.5.5.0-cn3
    db2wh_dbname: BLUDB
    # optionally you can provide the path to hold the generated db2 config for MAS
    db2wh_cfg_file: ~/maximoappsuite/devops-configs/config/db2.yml

    # Required to install MAS
    # -------------------------------------------------------------------------
    catalog_type: "{{ lookup('env', 'MAS_CATALOG_TYPE') | default('release', true) }}"
    mas_channel: "{{ lookup('env', 'MAS_CHANNEL') | default('8.x', true) }}"
    artifactory_username: "{{ lookup('env', 'W3_USERNAME') }}"
    artifactory_apikey: "{{ lookup('env', 'ARTIFACTORY_APIKEY') }}"
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
    icr_cp: "{{ lookup('env', 'ICR_CP') | default('cp.icr.io/cp', true) }}"
    icr_cpopen: "{{ lookup('env', 'ICR_CPOPEN') | default('icr.io/cpopen', true) }}"
    entitlement_username: "{{ lookup('env', 'ENTITLEMENT_USERNAME') | default('cp', true) }}"
    entitlement_key: "{{ lookup('env', 'ENTITLEMENT_KEY') }}"
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') | default('~/maximoappsuite/devops-configs/config', true) }}"
    mas_config:
      - "{{ mas_config_dir }}/bascfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/slscfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/mongocfg_masdev.yaml"
      - "{{ mas_config_dir }}/smtpcfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/ldapcfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/workspace_masdev.yaml"

  roles:
    - mas.devops.ocp_provision
    - mas.devops.ocp_setup_mas_deps
    - mas.devops.ocp_setup_ocs
    - mas.devops.cp4d
    - mas.devops.cp4d_db2wh
    - mas.devops.suite_install
    - mas.devops.suite_config
    - mas.devops.suite_verify
