---
- hosts: localhost
  any_errors_fatal: true

# 1. Deploy & configure the cluster
# -----------------------------------------------------------------------------
- name: Deploy & configure ROKS cluster in IBM Cloud
  import_playbook: ocp/provision-roks.yml

# 2. Install AMQ Streams
- name: Install AMQ Streams (Apache Kafka)
  import_playbook: dependencies/install-amqstreams.yml
  vars:
    kafka_namespace: amq-streams
    kafka_cluster_name: maskafka
    kafka_cluster_size: "{{ lookup('env', 'KAFKA_CLUSTER_SIZE') | default('small', true) }}"
    kafka_storage_class: ibmc-block-gold
    kafka_user_name: masuser
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') | default('~/maximoappsuite/devops-configs/config', true) }}"
    kafka_cfg_file: "{{ mas_config_dir }}/kafka.yml"


# 3. Install CP4D
# -----------------------------------------------------------------------------
- name: Install CP4D
  import_playbook: cp4d/install-cp4d.yml

# 4. Install & configure Db2
#-----------------------------------------------------------------------------
- name: Install & configure Db2
  import_playbook: cp4d/install-db2.yml
  vars:
    cpd_storage_class: ibmc-file-gold-gid
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') | default('~/maximoappsuite/devops-configs/config', true) }}"
    db2wh_cfg_file: "{{ mas_config_dir }}/db2.yml"

# 5. Install & configure MAS
# -----------------------------------------------------------------------------
- name: Install & configure MAS
  import_playbook: mas/install-suite.yml
  vars:
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') | default('~/maximoappsuite/devops-configs/config', true) }}"
    mas_config:
      - "{{ mas_config_dir }}/bascfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/slscfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/mongocfg_masdev.yaml"
      - "{{ mas_config_dir }}/smtpcfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/ldapcfg_masdeps1.yaml"
      - "{{ mas_config_dir }}/workspace_masdev.yaml"
      - "{{ mas_config_dir }}/db2.yml"
      - "{{ mas_config_dir }}/kafka.yml"
