---
- hosts: localhost
  any_errors_fatal: true
  vars:
    cpd_registry: cp.icr.io
    cpd_registry_user: cp
    cpd_registry_password: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') }}"
    cpd_meta_namespace: cpd-meta-ops
    cpd_storage_class: "{{ lookup('env', 'CPD_STORAGE_CLASS') }}"
    cpd_assemblies:
      - spark

  roles:
    # - mas.devops.cp4d
    - mas.devops.cp4d_spark
