---
- hosts: localhost
  any_errors_fatal: true

# 1. Deploy & configure the cluster
# -----------------------------------------------------------------------------
- name: Deploy & configure ROKS cluster in IBM Cloud
  import_playbook: ocp/provision-roks.yml


# 2. Install MongoDb
# -----------------------------------------------------------------------------
- name: Install MongoDb (Community Edition)
  import_playbook: dependencies/install-mongodb-ce.yml
  vars:
    mongodb_storage_class: ibmc-block-gold
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"


# 3. Install CP4D services & configure Db2
#-----------------------------------------------------------------------------
- name: Install CP4D services & configure Db2
  import_playbook: cp4d/install-db2.yml
  vars:
    cpd_storage_class: ibmc-file-gold-gid
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

# Temporary hack for Manage, because the operator is missing critical
# database configuration that requires manual intervention to set up.
- name: Db2 configuration hack for Manage
  import_playbook: mas/hack-manage-db2.yml


# 4. Perform Airgap Install if required
#-----------------------------------------------------------------------------
- name: Airgap Install
  import_playbook: airgap/airgap-install.yml
  vars:
    use_internal_registry: true
    configure_network: true
    # don't copy images from these apps
    excludeImages: "ibm-mas-assist,ibm-mas-hputilities,ibm-mas-iot,ibm-mas-monitor,ibm-mas-predict,ibm-mas-safety,ibm-mas-visualinspection,ibm-sls"


# 5. Install & configure MAS
# -----------------------------------------------------------------------------
- name: Install & configure MAS
  import_playbook: mas/install-suite.yml
  vars:
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"


# 6. Install & Configure Manage application
# -----------------------------------------------------------------------------
- name: Install Manage
  import_playbook: mas/install-app.yml
  vars:
    mas_app_id: manage

# Note that this sample playbook is always assuming a workspace ID of masdev,
# this can easily be modified when creating your own playbooks.
- name: Configure Manage
  import_playbook: mas/configure-app.yml
  vars:
    mas_app_id: manage
    mas_workspace_id: masdev
