---
- hosts: localhost
  any_errors_fatal: true

# 1. Deploy & configure the cluster
# -----------------------------------------------------------------------------
- name: Deploy & configure ROKS cluster in IBM Cloud
  import_playbook: ocp/provision-roks.yml

# 2. Install MongoDb
# -----------------------------------------------------------------------------
- name: Install MongoDb (Community Edition)
  import_playbook: dependencies/install-mongodb-ce.yml
  vars:
    mongodb_storage_class: ibmc-block-gold
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

# 3. Install SLS
# -----------------------------------------------------------------------------
- name: Install SLS
  import_playbook: sls/install-sls.yml
  vars:
    sls_storage_class: ibmc-file-gold-gid
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') | default('~/maximoappsuite/devops-configs/config', true) }}"
    mongodb_cfg_file: "{{mas_config_dir}}/mongodb.yml"
    sls_cfg_file: "{{ mas_config_dir }}/sls.yml"

    # Default to re-using the MAS entitlement key if we do not provide a specific one for SLS
    sls_entitlement_username: "{{ lookup('env', 'SLS_ENTITLEMENT_USERNAME') | default(lookup('env', 'MAS_ENTITLEMENT_USERNAME'), true) }}"
    sls_entitlement_key:  "{{ lookup('env', 'SLS_ENTITLEMENT_KEY') | default(lookup('env', 'MAS_ENTITLEMENT_KEY'), true) }}"

    bootstrap:
      license_id:  "{{ lookup('env', 'SLS_LICENSE_ID') | default('', true) }}"
      registration_key: "{{ lookup('env', 'SLS_REGISTRATION_KEY') | default('', true) }}"
      entitlement_file: "{{mas_config_dir}}/entitlement.lic"

# 3. Perform Airgap Install if required
# -----------------------------------------------------------------------------
- name: Airgap Install
  import_playbook: airgap/airgap-install.yml
  vars:
    use_internal_registry: true
    configure_network: true
    # don't copy images from these apps
    excludeImages: "ibm-mas-assist,ibm-mas-hputilities,ibm-mas-iot,ibm-mas-manage,ibm-mas-monitor,ibm-mas-predict,ibm-mas-safety,ibm-mas-visualinspection,ibm-sls"


# 4. Install & configure MAS
# -----------------------------------------------------------------------------
- name: Install & configure MAS
  import_playbook: mas/install-suite.yml
  vars:
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
