---
- hosts: localhost
  vars:
    cluster_name: "{{ lookup('env', 'CLUSTER_NAME')}}"
    cluster_type: roks
    ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"

    ocp_version: "{{ lookup('env', 'OCP_VERSION') }}"

    roks_zone: "{{ lookup('env', 'ROKS_ZONE') | default('lon02', true) }}"
    roks_flavor: "{{ lookup('env', 'ROKS_FLAVOR') | default('b3c.16x64', true) }}"
    roks_workers: "{{ lookup('env', 'ROKS_WORKERS') | default('3', true) }}"
    roks_flags: "{{ lookup('env', 'ROKS_FLAGS') | default('', true) }}"
  tasks:
    - name: "Wait until the LocalVolume CRD is available"
      community.kubernetes.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: "localvolumes.local.storage.openshift.io"
        wait: yes
        wait_sleep: 10
        wait_timeout: 300 # 5 mins until we give up waiting for the CRD to get into the expected state
        wait_condition:
          type: NamesAccepted
          status: "True"
      register: localvolume_crd_info
      retries: 120 # ~approx 5 minutes before we give up waiting for the CRD to be created
      delay: 5 # seconds
      until:
        - localvolume_crd_info.resources is defined
        - localvolume_crd_info.resources | length > 0

    - name: "Wait until the Suite CRD is available"
      community.kubernetes.k8s_info:
        api_version: apiextensions.k8s.io/v1
        name: "suites.core.mas.ibm.com"
        kind: CustomResourceDefinition
        wait: yes
        wait_sleep: 10
        wait_timeout: 300 # 5 mins
        wait_condition:
          type: NamesAccepted
          status: True
      register: crd_info
      retries: 20
      delay: 5
      until:
        - crd_info.resources is defined
        - crd_info.resources | length > 0
    - name: Create IBM CLoud ROKS cluster
      shell: >
        echo
        "hello"

