---
# ───────────────────────────────────────────────────────────────────────────────
# Creating Docker Secrets
# ───────────────────────────────────────────────────────────────────────────────
# secret/arcgis-container-registry created
# [SUCCESS]
# secret/arcgis-container-registry labeled
# [SUCCESS]