---
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Ingress Controller
# ───────────────────────────────────────────────────────────────────────────────
# Using OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
# .......+.........+.+...+.....+.+..+.........+.........+.+.....+++++++++++++++++++++++++++++++++++++++*...+.......+.........+...+..+......+...+.+.........+.....+......+++++++++++++++++++++++++++++++++++++++*.............+......+.+.....+..........+....................+.+.....+............+...............+............+.+...+............+...+...........+...+.......+...........+...+............+............+...+...+.+...........+.........+.+...+.....+......+.+..+.......+..................+..+..................................+..+...................+...+..+.........+.+......+..+.+............+.....+.......+......+.....................+...+..+......+..........+.....+....+......+...+......+.....+.+........+....+.....+...+........................+....+..+............+.+.........+...+..+...+....+........+.+.....+.+.....+.+...+..+....+...............+...+...+...+..+...+.......+..+.+.........+......+.....+.+......+...+...........+...+............+...+...+...+.+......+....................+...+.........+.+..+.........+......+.......+.....+.......+...............+.....+......+...+....+..+.+........+.+......+............+..+...+.+...........+....+.....+.+......++++++
# .....+++++++++++++++++++++++++++++++++++++++*..........+...+............+...+..+...+.+++++++++++++++++++++++++++++++++++++++*...+.....+...+.+.....+...+.+......+......+.....+...+.+.....+......+.........+.+...+...............+..+............+...+....+......+........+....+..+.........+......+....+.........+........+.......+........+.......+......+..+....+..................+......+....................+.+....................+......+.......+..+......+.........+...+...............+.+..............+.......++++++
# -----
# secret/arcgis-interpod-cert-pem created
# secret/arcgis-interpod-cert-pem labeled
# secret/arcgis-interpod-cert-pem labeled
# secret/arcgis-interpod-cert-pfx created
# secret/arcgis-interpod-cert-pfx labeled
# secret/arcgis-interpod-cert-pfx labeled
# .+..+.......+..+++++++++++++++++++++++++++++++++++++++*....+......+........+.......+...+............+..+...+.........+...+.......+......+...+......+.....+...+......+++++++++++++++++++++++++++++++++++++++*........+...+.+..............+...............+...+...+....+...+........+.......+.........+......+........+....+.................+.+.........+...+..++++++
# ..........+......+.....+............+.+......+...+.....+.+..+...+++++++++++++++++++++++++++++++++++++++*...+..+...+.+............+...+...............+++++++++++++++++++++++++++++++++++++++*......+..+...+..........+........+......+......+.........+.+............+..+.........+....+..+.+.................+.+..+...+.....................+....+.....+.+...........+....+......+..+.......+...+...+.....+............+..........+.....+.+..+...............+...+....+...+...+.....+......+....+.........+........+....+.........+............+..+...............+...+...+....+...+..+......+....+..+................+..+.+..+............++++++
# -----
# secret/arcgis-ingress-cert-pem created
# secret/arcgis-ingress-cert-pem labeled
# configmap/arcgis-ingress-controller-nginx-config created
# configmap/arcgis-ingress-controller-tcp-services created
# configmap/arcgis-ingress-controller-udp-services created
# lease.coordination.k8s.io/arcgis-ingress-controller-leader created
# serviceaccount/arcgis-ingress-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-ingress-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-ingress-rolebinding created
# deployment.apps/arcgis-ingress-controller created
# service/arcgis-ingress-nginx created
# [SUCCESS]


# cmd_install_ingress_controller()
# {
#   header "Deploying Ingress Controller"

#   local deploy_script="${CWD}/.install/ingress-controller/deploy.sh"
#   run_command "VERSION_TAG=${VERSION_TAG} \
#                REGISTRY_REPO=${REGISTRY_REPO} \
#                VERBOSE=${VERBOSE} \
#                \"${deploy_script}\" ${CUSTOM_PROPERTIES}" "Deploy Ingress controller yaml"
# }