---
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Ingress Controller
# ───────────────────────────────────────────────────────────────────────────────
# Using OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
# .......+.........+.+...+.....+.+..+.........+.........+.+.....+++++++++++++++++++++++++++++++++++++++*...+.......+.........+...+..+......+...+.+.........+.....+......+++++++++++++++++++++++++++++++++++++++*.............+......+.+.....+..........+....................+.+.....+............+...............+............+.+...+............+...+...........+...+.......+...........+...+............+............+...+...+.+...........+.........+.+...+.....+......+.+..+.......+..................+..+..................................+..+...................+...+..+.........+.+......+..+.+............+.....+.......+......+.....................+...+..+......+..........+.....+....+......+...+......+.....+.+........+....+.....+...+........................+....+..+............+.+.........+...+..+...+....+........+.+.....+.+.....+.+...+..+....+...............+...+...+...+..+...+.......+..+.+.........+......+.....+.+......+...+...........+...+............+...+...+...+.+......+....................+...+.........+.+..+.........+......+.......+.....+.......+...............+.....+......+...+....+..+.+........+.+......+............+..+...+.+...........+....+.....+.+......++++++
# .....+++++++++++++++++++++++++++++++++++++++*..........+...+............+...+..+...+.+++++++++++++++++++++++++++++++++++++++*...+.....+...+.+.....+...+.+......+......+.....+...+.+.....+......+.........+.+...+...............+..+............+...+....+......+........+....+..+.........+......+....+.........+........+.......+........+.......+......+..+....+..................+......+....................+.+....................+......+.......+..+......+.........+...+...............+.+..............+.......++++++
# -----
# secret/arcgis-interpod-cert-pem created
# secret/arcgis-interpod-cert-pem labeled
# secret/arcgis-interpod-cert-pem labeled
# secret/arcgis-interpod-cert-pfx created
# secret/arcgis-interpod-cert-pfx labeled
# secret/arcgis-interpod-cert-pfx labeled
# .+..+.......+..+++++++++++++++++++++++++++++++++++++++*....+......+........+.......+...+............+..+...+.........+...+.......+......+...+......+.....+...+......+++++++++++++++++++++++++++++++++++++++*........+...+.+..............+...............+...+...+....+...+........+.......+.........+......+........+....+.................+.+.........+...+..++++++
# ..........+......+.....+............+.+......+...+.....+.+..+...+++++++++++++++++++++++++++++++++++++++*...+..+...+.+............+...+...............+++++++++++++++++++++++++++++++++++++++*......+..+...+..........+........+......+......+.........+.+............+..+.........+....+..+.+.................+.+..+...+.....................+....+.....+.+...........+....+......+..+.......+...+...+.....+............+..........+.....+.+..+...............+...+....+...+...+.....+......+....+.........+........+....+.........+............+..+...............+...+...+....+...+..+......+....+..+................+..+.+..+............++++++
# -----
# secret/arcgis-ingress-cert-pem created
# secret/arcgis-ingress-cert-pem labeled
# configmap/arcgis-ingress-controller-nginx-config created
# configmap/arcgis-ingress-controller-tcp-services created
# configmap/arcgis-ingress-controller-udp-services created
# lease.coordination.k8s.io/arcgis-ingress-controller-leader created
# serviceaccount/arcgis-ingress-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-ingress-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-ingress-rolebinding created
# deployment.apps/arcgis-ingress-controller created
# service/arcgis-ingress-nginx created
# [SUCCESS]


# cmd_install_ingress_controller()
# {
#   header "Deploying Ingress Controller"

#   local deploy_script="${CWD}/.install/ingress-controller/deploy.sh"
#   run_command "VERSION_TAG=${VERSION_TAG} \
#                REGISTRY_REPO=${REGISTRY_REPO} \
#                VERBOSE=${VERBOSE} \
#                \"${deploy_script}\" ${CUSTOM_PROPERTIES}" "Deploy Ingress controller yaml"
# }

- name: Create Certs
  vars:
    ingress_tls_secret_name: "changeit"
    base_name: ingress-controller
    temp_key_file: "{{ mas_config_dir }}/{{ base_name }}.keyfile.key.$$.tmp"
    temp_crt_file: "{{ mas_config_dir }}/{{ base_name }}.certificate.crt.$$.tmp"
    temp_interpod_pfx_file: "{{ mas_config_dir }}/{{ base_name }}.interpod.pfx.$$.tmp"
  shell: |
    openssl req -x509 -newkey rsa:2048 -nodes -keyout \"{{ temp_key_file }}\" -out \"{{ temp_crt_file }}\" -sha256 -days 3650 -subj \"/CN=*.{{ arcgis_namespace }}.{{ arcgis_k8s_cluster_dns_suffix }}\"
  register: openssl_1st_cmd

- debug:
    var: openssl_1st_cmd
