---
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Prometheus RBAC
# ───────────────────────────────────────────────────────────────────────────────
# serviceaccount/arcgis-prometheus-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-prometheus-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-prometheus-rolebinding created
# [SUCCESS]