---
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Prometheus RBAC
# ───────────────────────────────────────────────────────────────────────────────
# serviceaccount/arcgis-prometheus-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-prometheus-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-prometheus-rolebinding created
# [SUCCESS]

- name: Create prometheus rbacs
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/prometheus/prometheus-rbac.yml.j2'
