---
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Queue Store RBAC
# ───────────────────────────────────────────────────────────────────────────────
# serviceaccount/arcgis-queue-serviceaccount created
# role.rbac.authorization.k8s.io/arcgis-queue-role created
# rolebinding.rbac.authorization.k8s.io/arcgis-queue-rolebinding created
# [SUCCESS]