---
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Help
# ───────────────────────────────────────────────────────────────────────────────
# service/arcgis-help created
# deployment.apps/arcgis-help created
# Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
# ingress.networking.k8s.io/arcgis-help-ingress created
# [SUCCESS]