---
# ───────────────────────────────────────────────────────────────────────────────
# Checking System Requirements...
# ───────────────────────────────────────────────────────────────────────────────
#     Checking operating system ......................................... WARNING
#         [33mMacOS is not a supported operating system.  Check the ArcGIS
#         Enterprise on Kubernetes System Requirements for supported
#         platforms.(B[m
#     Checking for kubectl .............................................. OK
#     Checking kubeconfig context ....................................... OK
#     Checking Kubernetes version ....................................... OK
#     Checking for support scripts ...................................... OK
#     Checking for arcgis-enterprise yaml ............................... OK
#     Checking for OpenSSL .............................................. OK
#     Checking for OS ................................................... OK