---
# ───────────────────────────────────────────────────────────────────────────────
# Deploying Manager
# ───────────────────────────────────────────────────────────────────────────────
# deployment.apps/arcgis-enterprise-manager created
# service/arcgis-enterprise-manager created
# Warning: annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
# ingress.networking.k8s.io/arcgis-ingress-enterprise-manager created
# [SUCCESS]