---
# Waiting for pods to startup...

# POD                                                  STATUS
# arcgis-rest-administrator-api-5b758794bb-dh6nk       Running
# arcgis-help-cdfb598b7-d88tp                          Running
# arcgis-enterprise-manager-59554bf9bc-sv9v2           Running
# arcgis-ingress-controller-6f857d5fdb-4cdg7           Running

# Waiting for site availability.......Ready
# ───────────────────────────────────────────────────────────────────────────────
#                            S U C C E S S !
# ───────────────────────────────────────────────────────────────────────────────
# ArcGIS Enterprise 11.2 on Kubernetes 11.2.0.5207 has been successfully deployed.

# Create the ingress or OpenShift route resource now, if you have not done so yet.

# The secure route should direct traffic to the arcgis-ingress-nginx service
# using either re-encrypt or passthrough for TLS termination.

# If using a DNS alias, you should create a CNAME record that resolves
# the DNS alias to the canonical router hostname for the cluster.

# Use the following URL to access the ArcGIS Enterprise 11.2 on Kubernetes
# Setup Wizard and configure your organization:

#     https://arcgis.apps.hpdevops.cp.fyre.ibm.com/arcgis/manager

# Use this URL to access ArcGIS Enterprise 11.2 on Kubernetes help:

#     https://arcgis.apps.hpdevops.cp.fyre.ibm.com/arcgis/help/en/