---
# ───────────────────────────────────────────────────────────────────────────────
# Running Validation Checks...
# ───────────────────────────────────────────────────────────────────────────────
# Validating property values...
# Validating sitename...
# Validating namespace...
# Validating kubectl user...
# Validating encryption keyfile...
# Validating registry host...