---
- name: "Checking system requirements (1/11)"
  include_tasks: "tasks/01-check-system-requirements.yml"

- name: "Running Validation Checks (2/11)"
  include_tasks: "tasks/02-run-validation-checks.yml"

- name: "Creating Docker Secrets (3/11)"
  include_tasks: "tasks/03-create-docker-secrets.yml"

- name: "Deploying Ingress Controller (4/11)"
  include_tasks: "tasks/04-deploy-ingress-controller.yml"

- name: "Deploying Prometheus RBAC (5/11)"
  include_tasks: "tasks/05-deploy-prometheus-rbac.yml"

- name: "Deploying Queue Store RBAC (6/11)"
  include_tasks: "tasks/06-deploy-queue-store-rbac.yml"

- name: "Deploying Elasticsearch rbac (7/11)"
  include_tasks: "tasks/07-deploy-elasticsearch-rbac.yml"

- name: "Deploying Admin API (8/11)"
  include_tasks: "tasks/08-deploy-admin-api.yml"

- name: "Deploying Help (9/11)"
  include_tasks: "tasks/09-deploy-help.yml"

- name: "Deploying Manager (10/11)"
  include_tasks: "tasks/10-deploy-manager.yml"

- name: "Waiting for pods to startup (11/11)"
  include_tasks: "tasks/11-wait-pods-startup.yml"
