---
apiVersion: apps.mas.ibm.com/v1
kind: ManageApp
metadata:
  name: "{{ mas_instance_id }}"
  namespace: "mas-{{ mas_instance_id }}-manage"
  labels:
    mas.ibm.com/instanceId: "{{ mas_instance_id }}"
    mas.ibm.com/applicationId: manage
spec: {}
