apiVersion: apps.mas.ibm.com/v1
kind: ManageWorkspace
metadata:
  name: "{{instance_id}}-{{workspace_id}}"
  namespace: "mas-{{instance_id}}-manage"
  labels:
    mas.ibm.com/instanceId: "{{instance_id}}"
    mas.ibm.com/workspaceId: "{{workspace_id}}"
    mas.ibm.com/applicationId: manage
spec:
    bindings:
      jdbc: workspace-application    
    components:
      base:
        version: 1.0.0-pre.stable      
    settings:
      db:
        dbSchema: maximo
        encryptionSecret: managedev-encryption-secret
        maxinst:
          bypassUpgradeVersionCheck: false
          db2Vargraphic: true
          demodata: true
          indexSpace: MAXINDEX
          tableSpace: MAXDATA
      deployment:
        buildTag: latest
        mode: up
        persistentVolumes: []
        serverBundles:         
          - bundleType: all
            isDefault: true
            isUserSyncTarget: true
            name: all
            replica: 1
            routeSubDomain: all
      languages:
        baseLang: EN
        secondaryLangs:
          - FR
          - IT
