apiVersion: apps.mas.ibm.com/v1
kind: ManageApp
metadata:
  name: "{{ instance_id }}"
  namespace: "mas-{{ instance_id }}-manage"
  labels:
    mas.ibm.com/instanceId: "{{ instance_id }}"
    mas.ibm.com/applicationId: manage
spec: {}
