apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-manage-operators
  namespace: openshift-marketplace
spec:
  displayName: IBM Manage Catalog (Dev)
  publisher: IBM
  description: Catalog Source for IBM  Manage
  sourceType: grpc
  image: wiotp-docker-local.artifactory.swg-devops.com/cpopen/ibm-mas-manage-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
