---
- debug:
    msg:
      - "IBM Licensing channel ..................... {{ ibm_licensing_channel }}"
      - "IBM Licensing version ..................... {{ ibm_licensing_version }}"

- name: "install-cp4d : Install IBM Licensing Subscription"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/licensing/subscription.yml.j2'

# 2. Patch ZenService lite-cr to set the zen version and increase resource limits
# ----------------------------------------------------------------------------------------------
- name: "install-cp4d : Wait for ibm-licensing-operator to be ready (60s delay)"
  kubernetes.core.k8s_info:
    api_version: apps/v1
    name: ibm-licensing-operator
    namespace: "{{ cpd_cs_control_namespace }}"
    kind: Deployment
  register: licensing_operator_lookup
  until: licensing_operator_lookup.resources[0].status.availableReplicas is defined
  retries: 20 # Approximately 20 minutes before we give up
  delay: 60 # 1 minute

- name: "install-cp4d : Install IBM Licensing Custom Resource"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/licensing/cr.yml.j2'

# 2.2 Wait for lite-cr to be created ...
- name: "install-cp4d : Wait for IBMLicensing instance to be created"
  kubernetes.core.k8s_info:
    api_version: operator.ibm.com/v1alpha1
    name: instance
    namespace: "{{ cpd_cpfs_namespace }}"
    kind: IBMLicensing
  register: licensingcr_output
  until:
    - licensingcr_output.resources is defined
    - licensingcr_output.resources | length > 0
    - licensingcr_output.resources[0].status.state is defined
    - licensingcr_output.resources[0].status.state == "ACTIVE"
  retries: 60 # approx 30 minutes before we give up
  delay: 30 # seconds

- name: "install-cp4d : Wait for ibm-licensing-service-instance to be ready (60s delay)"
  kubernetes.core.k8s_info:
    api_version: apps/v1
    name: ibm-licensing-service-instance
    namespace: "{{ cpd_cs_control_namespace }}"
    kind: Deployment
  register: licensing_instance_deployment_lookup
  until: licensing_instance_deployment_lookup.resources[0].status.availableReplicas is defined
  retries: 20 # Approximately 20 minutes before we give up
  delay: 60 # 1 minute