---
- debug:
    msg:
      - "IBM Namespace Scope channel ..................... {{ ibm_licensing_channel }}"

- name: "install-cp4d : Install IBM Namespace Scope Subscription"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/namespacescope/subscription.yml.j2'

# 2. Patch ZenService lite-cr to set the zen version and increase resource limits
# ----------------------------------------------------------------------------------------------
- name: "install-cp4d : Wait for ibm-namespace-scope-operator to be ready (60s delay)"
  kubernetes.core.k8s_info:
    api_version: apps/v1
    name: ibm-namespace-scope-operator
    namespace: "{{ cpd_operators_namespace }}"
    kind: Deployment
  register: ns_operator_lookup
  until: ns_operator_lookup.resources[0].status.availableReplicas is defined
  retries: 20 # Approximately 20 minutes before we give up
  delay: 60 # 1 minute

- name: "install-cp4d : Install IBM Namespace Scope Custom Resource"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/namespacescope/cr.yml.j2'

# 2.2 Wait for lite-cr to be created ...
- name: "install-cp4d : Wait for NamespaceScope common-service instance is ready"
  kubernetes.core.k8s_info:
    api_version: operator.ibm.com/v1
    name: common-service
    namespace: "{{ cpd_operators_namespace }}"
    kind: NamespaceScope
  register: ns_cr_lookup
  until:
    - ns_cr_lookup.resources is defined
    - ns_cr_lookup.resources | length > 0
    - ns_cr_lookup.resources[0].status.validatedMembers is defined
    - ns_cr_lookup.resources[0].status.validatedMembers | length > 1
  retries: 60 # approx 30 minutes before we give up
  delay: 30 # seconds
