---
- debug:
    msg:
      - "IBM Foundational Services channel ......... {{ cpfs_channel }}"
      - "IBM Foundational Services version ......... {{ cpfs_version }}"

- name: "install-cp4d : Install common-services-maps configmap"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/cpfs/common-service-maps-cm.yml.j2'

- name: "install-cp4d : Install IBM Foundational Services Subscription"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/cpfs/subscription.yml.j2'

# 2. Patch ZenService lite-cr to set the zen version and increase resource limits
# ----------------------------------------------------------------------------------------------
- name: "install-cp4d : Wait for ibm-common-service-operator to be ready (60s delay)"
  kubernetes.core.k8s_info:
    api_version: apps/v1
    name: ibm-common-service-operator
    namespace: "{{ cpd_operators_namespace }}"
    kind: Deployment
  register: cpfs_operator_lookup
  until: cpfs_operator_lookup.resources[0].status.availableReplicas is defined
  retries: 20 # Approximately 20 minutes before we give up
  delay: 60 # 1 minute

- name: "install-cp4d : Install IBM Foundational Services Custom Resource"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/cpfs/cr.yml.j2'

- name: "install-cp4d : Wait for CommonService instance to be ready in {{ cpd_operators_namespace }}"
  kubernetes.core.k8s_info:
    api_version: operator.ibm.com/v3
    name: common-service
    namespace: "{{ cpd_operators_namespace }}"
    kind: CommonService
  register: commonservices_operators_output
  until:
    - commonservices_operators_output.resources is defined
    - commonservices_operators_output.resources | length > 0
    - commonservices_operators_output.resources[0].status.overallStatus is defined
    - commonservices_operators_output.resources[0].status.overallStatus == "Succeeded"
    - commonservices_operators_output.resources[0].status.phase is defined
    - commonservices_operators_output.resources[0].status.phase == "Succeeded"
  retries: 60 # approx 30 minutes before we give up
  delay: 30 # seconds

- name: "install-cp4d : Wait for CommonService instance to be ready in {{ cpd_instance_namespace }}"
  kubernetes.core.k8s_info:
    api_version: operator.ibm.com/v3
    name: common-service
    namespace: "{{ cpd_instance_namespace }}"
    kind: CommonService
  register: commonservices_operators_output
  until:
    - commonservices_operators_output.resources is defined
    - commonservices_operators_output.resources | length > 0
    - commonservices_operators_output.resources[0].status.phase is defined
    - commonservices_operators_output.resources[0].status.phase == "Succeeded"
  retries: 60 # approx 30 minutes before we give up
  delay: 30 # seconds