apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-truststore-mgr-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Truststore Manager Catalog (Dev)
  publisher: IBM
  description: Catalog Source for IBM Truststore Manager (Internal Use Only)
  sourceType: grpc
  image: wiotp-docker-local.artifactory.swg-devops.com/cpopen/ibm-truststore-mgr-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
