---

# 1. Create namespace we will deploy to
- name: "setup/operator : Create namespace"
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: '{{ sls_namespace }}'

# 2. Create the operator group that will scope the operator
- name: "setup/operator : Create operator group"
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/operator-group.yaml') }}"
    wait: yes
    wait_timeout: 60 #subsequent tasks will fail if the CRD isn't fully created

# 3. Create the subscription for the ibm-sls operator
- name: "setup/operator : Create subscription"
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/subscription.yaml') }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: 'CatalogSourcesUnhealthy'
      status: "False"
  register: _sls_subscription

# 4. Wait for the operator to be ready
# TODO: Create a better wait condition instead of a 1 minute fixed sleep
- name: "setup/operator : Sleep for 1 minute"
  pause:
    seconds: 60

