---
- name: Install Service Mesh Operator
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/servicemesh/service-mesh-install.yml') }}"
    namespace: "{{ serviceMeshNamespace }}"

---
- name: Wait for Service Mesh Operator to be ready
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/servicemesh/service-mesh-configure.yml') }}"
    namespace: "{{ serviceMeshNamespace }}"
