---
# Install Operator & create entitlement openshift-serverless
# -----------------------------------------------------------------------------
- name: "Install Openshift Serverless Operator"
  ansible.builtin.include_role:
    name: ibm.mas_devops.install_operator
  vars:
    namespace: "{{ serverless_namespace }}"
    icr_username: "{{ ibm_entitlement_username }}"
    icr_password: "{{ ibm_entitlement_key }}"
    catalog_source: "{{ serverless_catalog_source }}"
    operator_group: "{{ lookup('template', 'templates/serverless/operator-group.yml.j2') }}"
    subscription: "{{ lookup('template', 'templates/serverless/subscription.yml.j2') }}"
# - name: "community : install : serverlessservices CRD "
#   kubernetes.core.k8s:
#     apply: yes
#     definition: "{{ lookup('template', 'templates/serverless/serverless-services-crd.yml.j2') }}"

# - name: "community : install : ServerLess services CR "
#   kubernetes.core.k8s:
#     apply: yes
#     definition: "{{ lookup('template', 'templates/serverless/serverless-services-cr.yml.j2') }}"

# Install KnativeServing
# -----------------------------------------------------------------------------
# - name: "community : install : KnativeServing CR "
#   kubernetes.core.k8s:
#     apply: yes
#     definition: "{{ lookup('template', 'templates/serverless/knative-serverless-cr.yml.j2') }}"

# Install the CRD
# -----------------------------------------------------------------------------
# - name: "community : install : Install Openshift Serverless Operator CRD"
#   kubernetes.core.k8s:
#     apply: yes
#     definition: "{{ lookup('template', 'templates/serverless/crd.yml.j2') }}"

# Install the operator
# -----------------------------------------------------------------------------
# - name: "community : install : Install the MongoDb Operator"
#   kubernetes.core.k8s:
#     apply: yes
#     definition: "{{ lookup('template', 'templates/serverless/manager.yml.j2') }}"
#     wait: yes
#     wait_condition:
#       status: "True"
#       type: Available
# Install the CR
# -----------------------------------------------------------------------------
# - name: "community : install : Create MongoDb cluster"
#   kubernetes.core.k8s:
#     apply: yes
#     definition: "{{ lookup('template', 'templates/serverless/cr.yml.j2') }}"

# - name: Create openshift-serverless subscription
#   k8s:
#     apply: yes
#     definition: "{{ lookup('template', 'templates/serverless/subscription.yml.j2') }}"
#     namespace: "{{ serverlessNamespace }}"

# - name: Create openshift-serverless operator
#   k8s:
#     apply: yes
#     definition: "{{ lookup('template', 'templates/serverless/operator-group.yml') }}"
#     namespace: "{{ serverlessNamespace }}"

# - name: Deploy openshift-serverless operator
#   k8s:
#     apply: yes
#     definition: "{{ lookup('template', 'templates/serverless/knative-openshift-deployment.yml') }}"
#     namespace: "{{ serverlessNamespace }}"
