---
- name: Create openshift-serverless subscription
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/serverless/subscription.yml') }}"
    namespace: "{{ serverlessNamespace }}"

- name: Create openshift-serverless operator
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/serverless/operator-group.yml') }}"
    namespace: "{{ serverlessNamespace }}"

- name: Deploy openshift-serverless operator
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/serverless/knative-openshift-deployment.yml') }}"
    namespace: "{{ serverlessNamespace }}"
