---
# Install Operator & create entitlement openshift-authorino
# -----------------------------------------------------------------------------
- name: "Install Openshift authorino Operator"
  ansible.builtin.include_role:
    name: ibm.mas_devops.install_operator
  vars:
    namespace: "{{ openshift_namespace }}"
    icr_username: "{{ ibm_entitlement_username }}"
    icr_password: "{{ ibm_entitlement_key }}"
    catalog_source: "{{ serverless_catalog_source }}"
    operator_group: "{{ lookup('template', 'templates/authorino/operator-group.yml.j2') }}"
    subscription: "{{ lookup('template', 'templates/authorino/subscription.yml.j2') }}"
# Install Authorino TODO: failing now
# -----------------------------------------------------------------------------
# - name: "community : install : Authorino"
#   kubernetes.core.k8s:
#     apply: yes
#     definition: "{{ lookup('template', 'templates/authorino/cr.yml.j2') }}"
