---
- name: Create Service Mesh subscription
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/servicemesh/subscription.yml') }}"
    namespace: "{{ serviceMeshNamespace }}"

- name: Create Service Account for Service Mesh
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/servicemesh/service-account.yml') }}"
    namespace: "{{ serviceMeshNamespace }}"

- name: Deploy service mash operator
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/servicemesh/service-mesh-deployment.yml') }}"
    namespace: "{{ serviceMeshNamespace }}"
