---
- name: Load variables (main)
  include_vars: "vars/main.yml"

# Deploy OpenShift Serverless
# -----------------------------------------------------------------------------
- include_tasks: tasks/deploy_serverless.yml
# - include_tasks: tasks/deploy_servicemesh.yml
- include_tasks: tasks/deploy_authorino.yml
- include_tasks: tasks/deploy_odh.yml
