---
- name: Load variables (main)
  include_vars: "vars/main.yml"

# Deploy OpenShift Serverless operators
# -----------------------------------------------------------------------------
- include_tasks: tasks/serverless-operator.yml
- include_tasks: tasks/servicemesh-operator.yml
- include_tasks: tasks/authorino-operator.yml
- include_tasks: tasks/odh-operator.yml

# Create Aibroker namespace
# -----------------------------------------------------------------------------
- name: "Create Namespace"
  kubernetes.core.k8s:
    template: "templates/aibroker/namespace.yml.j2"

# Create Storage class
# -----------------------------------------------------------------------------
- name: "Create Storage class"
  kubernetes.core.k8s:
    template: "templates/aibroker/storage-class.yml.j2"

# Create DSCInitialization instance
# -----------------------------------------------------------------------------
- name: "Create DSCInitialization instance"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/odh/default-dsci.yml.j2') }}"

- name: "Wait for the DSCInitialization instance to be ready"
  kubernetes.core.k8s_info:
    api_version: dscinitialization.opendatahub.io/v1
    name: default-dsci
    namespace: opendatahub
    kind: DSCInitialization
  register: dsci_lookup
  until:
    - dsci_lookup.resources is defined and dsci_lookup.resources | length == 1
    - dsci_lookup.resources[0].status is defined
    - dsci_lookup.resources[0].status.phase is defined
    - dsci_lookup.resources[0].status.phase == 'Ready'
  retries: 10
  delay: 30

# Create Data Science Cluster
- name: "Create Data Science Cluster"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/odh/data-science-cluster.yml.j2') }}"

# Create Data Science Pipelines Applications
- name: "Create Create Data Science Pipelines Applications CR"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/odh/dspa-local-dev.yml.j2') }}"
