---
# Install Operator & create entitlement openshift-odh
# -----------------------------------------------------------------------------
- name: "Install Openshift odh Operator"
  ansible.builtin.include_role:
    name: ibm.mas_devops.install_operator
  vars:
    namespace: "{{ openshift_namespace }}"
    icr_username: "{{ ibm_entitlement_username }}"
    icr_password: "{{ ibm_entitlement_key }}"
    catalog_source: "{{ odh_catalog_source }}"
    operator_group: "{{ lookup('template', 'templates/odh/operator-group.yml.j2') }}"
    subscription: "{{ lookup('template', 'templates/odh/subscription.yml.j2') }}"

# Wait until the Opendata Hub CRD is available
# -----------------------------------------------------------------------------
- name: "Wait until the Opendata Hub CRD is available"
  include_tasks: "{{ role_path }}/../../common_tasks/wait_for_crd.yml"
  vars:
    crd_name: knativeservings.operator.knative.dev
# TODO: add wait for operator success

