---
# Install Operator & create entitlement openshift-odh
# -----------------------------------------------------------------------------
- name: "Install Openshift odh Operator"
  ansible.builtin.include_role:
    name: ibm.mas_devops.install_operator
  vars:
    namespace: "{{ openshift_namespace }}"
    icr_username: "{{ ibm_entitlement_username }}"
    icr_password: "{{ ibm_entitlement_key }}"
    catalog_source: "{{ odh_catalog_source }}"
    operator_group: "{{ lookup('template', 'templates/odh/operator-group.yml.j2') }}"
    subscription: "{{ lookup('template', 'templates/odh/subscription.yml.j2') }}"

- name: "deploy startCSV"
  debug:
    msg: "Starting CSV ... {{ odh_operator_version }}"

- name: Approve install plan for Opendatahub operator
  block:
    - name: Lookup install plan to approve
      shell: oc get installplan -n openshift-operators | awk 'NR>1 {print $1}'
      register: installPlan
    - name: debug
      debug:
        msg: "{{ installPlan.stdout }}"
    - name: Approve install plan to approve
      shell: oc patch installplan {{ installPlan.stdout_lines[0] }} -n openshift-operators --type merge --patch '{"spec":{"approved":true}}'

# Wait until the Opendata Hub CRD is available
# -----------------------------------------------------------------------------
- name: "Wait until the Opendata Hub CRD is available"
  include_tasks: "{{ role_path }}/../../common_tasks/wait_for_crd.yml"
  vars:
    crd_name: knativeservings.operator.knative.dev
# TODO: add wait for operator success

- name: "Wait for Opendata Hub instance to be ready in {{ openshift_namespace }}"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    name: "{{ odh_operator_version }}"
    namespace: "{{ openshift_namespace }}"
    kind: ClusterServiceVersion
  register: odh_operators_output
  until:
    - odh_operators_output.resources is defined
    - odh_operators_output.resources | length > 0
    - odh_operators_output.resources[0].status.phase is defined
    - odh_operators_output.resources[0].status.phase == "Succeeded"
  retries: 60 # approx 30 minutes before we give up
  delay: 30 # seconds
