---
# Install Operator & create entitlement openshift-odh
# -----------------------------------------------------------------------------
- name: "Install Openshift odh Operator"
  ansible.builtin.include_role:
    name: ibm.mas_devops.install_operator
  vars:
    namespace: "{{ openshift_namespace }}"
    icr_username: "{{ ibm_entitlement_username }}"
    icr_password: "{{ ibm_entitlement_key }}"
    catalog_source: "{{ odh_catalog_source }}"
    operator_group: "{{ lookup('template', 'templates/odh/operator-group.yml.j2') }}"
    subscription: "{{ lookup('template', 'templates/odh/subscription.yml.j2') }}"

# Wait until the Opendata Hub CRD is available
# -----------------------------------------------------------------------------
- name: "Wait until the Opendata Hub CRD is available"
  include_tasks: "{{ role_path }}/../../common_tasks/wait_for_crd.yml"
  vars:
    crd_name: knativeservings.operator.knative.dev
# TODO: add wait for operator success

# - name: "Wait for all operators to be Succeeded"
#   kubernetes.core.k8s_info:
#     api_version: operators.coreos.com/v1alpha1
#     namespace: openshift-operators
#     #name: authorino-operator.v0.11.1
#     #name: opendatahub-operator.v2.12.0
#     #name: serverless-operator.v1.32.1
#     #name: servicemeshoperator.v2.5.1
#     kind: ClusterServiceVersion
#   register: odh_lookup
#   until:
#     - odh_lookup.resources is defined and odh_lookup.resources | length == 1
#     # - odh_lookup.resources[0].status is defined
#     # - odh_lookup.resources[0].status.phase is defined
#     - odh_lookup.resources[0].status.phase == 'Succeeded'
#   retries: 20
#   delay: 30

- name: "debug operators"
  debug:
    msg: "{{ odh_lookup.resources[0].status.phase }}"
