---
# Check db2 restore required variables
# -----------------------------------------------------------------------------
- name: "Fail if db2_restore_instance_name is not provided"
  assert:
    that: db2_restore_instance_name is defined and db2_restore_instance_name != ""
    fail_msg: "db2_restore_instance_name is required"


# Set common restore variables
# -----------------------------------------------------------------------------
- name: "Set fact: common restore variables"
  set_fact:
    masbr_job_component:
      name: "db2"
      namespace: "{{ db2_namespace }}"
      instance: "{{ db2_restore_instance_name }}"
    masbr_job_data_list:
      - seq: "1"
        type: "database"


# Before run tasks
# -------------------------------------------------------------------------
- name: "Before run tasks"
  include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/before_run_tasks.yml"
  vars:
    _job_type: "restore"
    _component_info_task_path: "{{ role_path }}/tasks/get-db2-info.yml"


# Create k8s Job to run restore tasks
# -----------------------------------------------------------------------------
- name: "Create k8s Job to run restore tasks"
  when: masbr_create_task_job
  include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/create_run_task_job.yml"
  vars:
    _rt_role_env:
      - name: "ROLE_NAME"
        value: "db2"
      - name: "DB2_ACTION"
        value: "{{ db2_action }}"


- name: "Run restore tasks"
  when: not masbr_create_task_job
  block:
    # Update restore job status: New
    # -------------------------------------------------------------------------
    - name: "Update restore job status: New"
      include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/update_job_status.yml"
      vars:
        _job_data_list:
          - seq: "1"
            phase: "New"


    # Get the backup job information specified by masbr_restore_from
    # -------------------------------------------------------------------------
    - name: "Get the backup job information specified by masbr_restore_from"
      include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/get_restore_from_job.yml"


    # Run restore tasks for each data type
    # -------------------------------------------------------------------------
    - name: "Run restore tasks for each data type"
      include_tasks: "{{ role_path }}/tasks/restore/restore-{{ job_data_item.type }}.yml"
      vars:
        masbr_job_data_seq: "{{ job_data_item.seq }}"
        masbr_job_data_type: "{{ job_data_item.type }}"
      loop: "{{ masbr_job_data_list }}"
      loop_control:
        loop_var: job_data_item

  rescue:
    # Update restore status: Failed
    # -------------------------------------------------------------------------
    - name: "Update database restore status: Failed"
      include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/update_job_status.yml"
      vars:
        _job_status:
          phase: "Failed"

  always:
    # After run tasks
    # -------------------------------------------------------------------------
    - name: "After run tasks"
      include_tasks: "{{ role_path }}/../../common_tasks/backup_restore/after_run_tasks.yml"
