---

- name: Enable dual stack on the fyre cluster for ipv6 test
  ansible.builtin.ssh:
    host: "{{ api_host }}"
    password: "{{ fyre_root_password}}"
  when:
    - ipv6_test=="true"

- name: Create script to enable dual stack in local /tmp
  ansible.builtin.template:
    src: "{{ role_path }}/files/enableIPv6.sh"
    dest: /tmp/enableIPv6.sh
    mode: '777'
  when:
    - ipv6_test=="true"

- name: "Enable IPv6 on this system"
  command: "bash /temp/enableIPv6.sh"
  when:
    - ipv6_test=="true"
