---

kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ arcgis_ingress_controller_nginx_config_map }}"
  namespace: "{{ arcgis_namespace }}"
  labels:
    arcgis/app: ingress-nginx
    arcgis/siteName: "{{ arcgis_sitename }}"
data:
  proxy-body-size: "{{ arcgis_ingress_controller_proxy_body_size }}"
  proxy-buffer-size: "{{ arcgis_ingress_controller_proxy_buffer_size }}"
  proxy-read-timeout: "{{ arcgis_ingress_controller_proxy_read_timeout }}"
  proxy-send-timeout: "{{ arcgis_ingress_controller_proxy_send_timeout }}"
  # Adding this 2 new properties so that standard X-Forwarded-* headers
  # and URI get passed through the Ingress Controller from the original request
  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers
  use-forwarded-headers: "{{ arcgis_ingress_controller_use_forwarded_headers }}"
  proxy-add-original-uri-header: "{{ arcgis_ingress_controller_proxy_add_original_uri_header }}"
  hsts: "{{ arcgis_ingress_controller_hsts_enabled }}"
  ssl-protocols: "{{ arcgis_ingress_controller_ssl_protocols }}"
  ssl-ciphers: "{{ arcgis_ingress_controller_ssl_ciphers }}"
  disable-access-log: "true"
  allow-snippet-annotations: "true"
  
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ arcgis_ingress_controller_tcp_services_config_map }}"
  namespace: "{{ arcgis_namespace }}"
  labels:
    arcgis/app: ingress-nginx
    arcgis/siteName: "{{ arcgis_sitename }}"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ arcgis_ingress_controller_udp_services_config_map }}"
  namespace: "{{ arcgis_namespace }}"
  labels:
    arcgis/app: ingress-nginx
    arcgis/siteName: "{{ arcgis_sitename }}"

---
# Ingress controller electionid lease
kind: Lease
apiVersion: coordination.k8s.io/v1
metadata:
  name: "{{ arcgis_ingress_controller_election_id }}"
  namespace: "{{ arcgis_namespace }}"
  labels:
    arcgis/app: ingress-nginx
    arcgis/siteName: "{{ arcgis_sitename }}"

---

