---
# This task can be used to verify if a secret is present in a namespace. It will fail if the secret does not exist.
# Primarily used to permit this check to be performed against a list of secrets using the loop keyword.
# Params:
#   secret_name: The name of the secret
#   namespace: The namespace the secret must exist in
# Return:
#   __check_secret_return: The secret resource (if found)
# Usage:
# - name: "Check required secrets are present"
#   ansible.builtin.include_tasks: "{{ role_path }}/../../common_tasks/check_secret.yml"
#   vars:
#     secret_name: "{{ item }}"
#     namespace: "mynamespace"
#   loop:
#     - "secret_a"
#     - "secret_b"
#     - "secret_c"

- name: "Lookup {{ secret_name }} secret in the namespace {{ namespace }}"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ namespace }}"
    name: "{{ secret_name }}"
  register: __check_secret_return
- name: "Fail if {{ secret_name }} secret does not exist in {{ namespace }}"
  fail:
    msg: "The required {{ secret_name }} secret does not exist in the namespace {{ namespace }}"
  when: __check_secret_return.resources | length == 0