---
# 1. Use the secret name provided by the user
# -----------------------------------------------------------------------------
- name: set ocp ingress tls secret
  when: ocp_ingress_tls_secret_name is not defined
  set_fact:
    ocp_ingress_tls_secret_name: "{{ lookup('env', 'OCP_INGRESS_TLS_SECRET_NAME') | default('router-certs-default', True) }}"


# 2. If the secret name wasn't provided directly then look it up
# -----------------------------------------------------------------------------
- name: Lookup the default ingress controller
  when: ocp_ingress_tls_secret_name is not defined
  k8s_info:
    api_version: operator.openshift.io/v1
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
  register: opc_default_ingress_controller

- name: Confirm that we can find the default certificate name
  when: ocp_ingress_tls_secret_name is not defined
  assert:
    that:
      - opc_default_ingress_controller.resources is defined
      - opc_default_ingress_controller.resources | length == 1
      - opc_default_ingress_controller.resources[0].spec is defined
      - opc_default_ingress_controller.resources[0].spec.defaultCertificate is defined
      - opc_default_ingress_controller.resources[0].spec.defaultCertificate.name is defined
      - opc_default_ingress_controller.resources[0].spec.defaultCertificate.name != ""
    fail_msg: "Unable to retrieve the name of the default ingress certificate from IngressController/default in the openshift-ingress-operator namespace"

- name: Register the default certificate name
  when: ocp_ingress_tls_secret_name is not defined
  set_fact:
    cluster_ingress_secret_name: "{{ opc_default_ingress_controller.resources[0].spec.defaultCertificate.name }}"


# 3. Retrieve the certificate content from the secret
# -----------------------------------------------------------------------------
- name: Lookup the default ingress certificate secret
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ cluster_ingress_secret_name }}"
    namespace: openshift-ingress
  register: cluster_ingress_secret

- name: Confirm that we can find the default certificate secret
  assert:
    that:
      - cluster_ingress_secret.resources is defined
      - cluster_ingress_secret.resources | length == 1
      - cluster_ingress_secret.resources[0].data is defined
      - cluster_ingress_secret.resources[0].data['tls.crt'] is defined
      - cluster_ingress_secret.resources[0].data['tls.crt'] != ""
    fail_msg: "Unable to retrieve the default ingress certificate from Secret/{{ cluster_ingress_secret_name }} in the openshift-ingress namespace"

- name: Register the default certificate
  set_fact:
    cluster_ingress_tls_crt: "{{ cluster_ingress_secret.resources[0].data['tls.crt'] | b64decode }}"


# 4. Debug Information
# -----------------------------------------------------------------------------
- name: "Debug cluster certificate secret search"
  debug:
    msg:
      - "Cluster Ingress Cert Secret Name ...... {{ cluster_ingress_secret_name | default('missing', True) }}"
      - "Cluster Ingress Cert .................. {{ cluster_ingress_tls_crt | default('missing', True) }}"
