---
# About this task:
# Use the appropriate cpd-cli manage command to create or update
# the global image pull secret with the appropriate credentials

# More details: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=cluster-updating-global-image-pull-secret

# Run the appropriate command to update the global image pull secret
- name: "cpd-cli : prereqs : Running command : Update global image pull secret"
  shell: |
    cpd-cli manage add-icr-cred-to-global-pull-secret \
    --entitled_registry_key={{ cpd_entitlement_key }} 2>&1 | tee {{ role_path }}/logs/cpd_platform_step2_cpd_config_image_pull_secret_output.log
  register: cpd_config_image_pull_secret_output
  failed_when: cpd_config_image_pull_secret_output.rc > 0 or ('add-icr-cred-to-global-pull-secret command ran successfully' not in cpd_config_image_pull_secret_output.stdout)

- name: "cpd-cli: prereqs : Debug command output : Update global image pull secret"
  debug:
    msg: "{{ cpd_config_image_pull_secret_output.stdout }}"
