---
# You must run the authorize-instance-topology command to apply the required permissions to the projects that are associated with an instance of IBM Cloud Pak for Data.
# The command:
# Creates the specified projects if they don't already exist.
# Creates the NamespaceScope operator in the operators project.
# Applies the require role to the operands project and any tethered projects.
# Binds the applied role to the service account of the NamespaceScope operator.
# More details: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-applying-required-permissions-projects-namespaces
- name: "cpd-cli: Run - Configure cpd namespaces"
  shell: |
    cpd-cli manage authorize-instance-topology \
    --cpd_operator_ns={{ cpd_operators_namespace }} \
    --cpd_instance_ns={{ cpd_instance_namespace }} 2>&1 | tee {{ role_path }}/logs/cpd_platform_step3_cpd_config_namespaces_output.log
  register: cpd_config_namespaces_output
  failed_when: cpd_config_namespaces_output.rc > 0 or ('authorize-instance-topology command ran successfully' not in cpd_config_namespaces_output.stdout)

- name: "cpd-cli: Debug - Configure cpd namespaces"
  debug:
    msg: "{{ cpd_config_namespaces_output.stdout }}"
