# This task installs the pre-requisites for IBM Cloud Pak for Data platform
# -----------------------------------------------------------------------------

# Updating the global image pull secret for IBM Cloud Pak for Data
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=cluster-updating-global-image-pull-secret
- include_tasks: "tasks/prereqs_cpd_platform/configure-image-pull-policy.yml"
  vars:
    cpd_log_filename: "cpd_platform_prereq_step1_update_image_pull_policy"

# Applying the required permissions to the projects (namespaces) for an instance of IBM Cloud Pak for Data
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-applying-required-permissions-projects-namespaces
- include_tasks: "tasks/prereqs_cpd_platform/configure-namespaces.yml"
  vars:
    cpd_log_filename: "cpd_platform_prereq_step2_configure_namespaces"

# Authorizing a user to act as an IBM Cloud Pak for Data instance administrator
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-authorizing-instance-administrator
- include_tasks: "tasks/prereqs_cpd_platform/authorize-user-cpd-admin.yml"
  vars:
    cpd_log_filename: "cpd_platform_prereq_step3_configure_rbac"
    
# Installing the IBM Cloud Pak foundational services and IBM licensing for Cloud Pak for Data
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-installing-cloud-pak-foundational-services
- include_tasks: "tasks/prereqs_cpd_platform/install-dependencies.yml"
  vars:
    cpd_log_filename: "cpd_platform_prereq_step4_install_dependencies"
