---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-cp-data-operator-group
  namespace: "{{ cpd_meta_namespace }}"
spec:
  targetNamespaces:
    - "{{ cpd_meta_namespace }}"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cp-data-operator
  namespace: "{{ cpd_meta_namespace }}"
spec:
  channel: v1.0
  installPlanApproval: Automatic
  name: ibm-cp-data-operator
  source: ibm-cp-data-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-cp-data-operator.v1.0.5
