---
# 1. Fetch IBM Cloud Resource Group Id and MongoDB Instance Id
# -----------------------------------------------------------------------------
- name: Retrieve resource group guid
  ibm.cloudcollection.ibm_resource_group_info:
    name: "{{ ibmcloud_resourcegroup }}"
    ibmcloud_api_key: "{{ ibmcloud_apikey }}"
  register: rg_info

- name: Debug Resource Group GUID
  debug:
    msg:
      - "Resource Group GUID ... {{ rg_info.resource.id }}"
      - "{{ibm_mongo_name}}"
      - "{{ibm_mongo_service}}"
      - "{{ibm_mongo_location}}"
- name: Set resource group guid variable
  when:
    - rg_info.resource.id is defined
  set_fact:
    resourceGID: "{{ rg_info.resource.id }}"

- name: Fetch Mongo DB Instance information
  ibm.cloudcollection.ibm_database_info:
    name: "{{ ibm_mongo_name }}"
    ibmcloud_api_key: "{{ ibmcloud_apikey }}"
    resource_group_id: "{{ resourceGID }}"
    service: "{{ ibm_mongo_service }}"
    region: "{{ ibm_mongo_location }}"
  register: existing_mongodb_info

- name: Debug, MongoDB Resource Id
  debug:
    msg:
      - "Mongo Info ........... {{ existing_mongodb_info.resource.id }}"

# 2. Create mongo service credentials and k8s secret in mas_config directory
# -----------------------------------------------------------------------------
- name: Create IBM Cloud resource key for mongodb (service id and apikey will be created automatically)
  ibm.cloudcollection.ibm_resource_key:
    name: "key-{{ mongo_service_credentials_secret_name }}"
    resource_instance_id: "{{ existing_mongodb_info.resource.id }}"
    role: "Editor"
    region: "{{ ibm_mongo_location }}"
    ibmcloud_api_key: "{{ ibmcloud_apikey }}"
  register: mongo_resource_key_info

- name: Fail if unable to create service creddentials for mongo
  assert:
    that:
      - mongo_resource_key_info.resource.credentials['connection.mongodb.authentication.username'] != ''
    fail_msg: "Not able to create Service Credentials for MongoDB in IBMCloud"

- name: Debug Mongo Service credentials info
  debug:
    msg:
      - "Username .................................... {{ mongo_resource_key_info.resource.credentials['connection.mongodb.authentication.username'] }}"

- name: Set the var for mongo_host_port_string from TF output
  set_fact:
    mongo_host_port_string: "{{ existing_mongodb_info.resource.connectionstrings[0].composed.split('@')[1].split('/')[0] }}"

- name: Set the var for mongo hosts and ports
  set_fact:
    mongo_host_0: "{{ existing_mongodb_info.resource.connectionstrings[0].hosts[0].hostname }}"
    mongo_host_1: "{{ existing_mongodb_info.resource.connectionstrings[0].hosts[1].hostname }}"
    mongo_host_2: "{{ existing_mongodb_info.resource.connectionstrings[0].hosts[2].hostname }}"
    mongo_port: "{{ existing_mongodb_info.resource.connectionstrings[0].hosts[0].port }}"

- name: Create k8s Secret for mongo service credentials
  ansible.builtin.template:
    src: ibm/mongo_service_credentials_secret.yml.j2
    dest: "{{ mas_config_dir }}/{{ mongo_service_credentials_secret_name }}.yml"

