---
- name: Load variables (main)
  include_vars: "vars/main.yml"

- include_tasks: tasks/tenant/main.yml
# TODO: create_apikey.sh, delete_apikey.sh, update_apikey.sh
# TODO: create_s3.sh, delete_s3.sh
# TODO: create_wx.sh, delete_wx.sh
