---
- name: Load variables (main)
  include_vars: "vars/main.yml"

# TODO: create_apikey.sh, delete_apikey.sh, update_apikey.sh in one role
# TODO: create_bucket.py, delete_bucket.py
# TODO: create_s3.sh, delete_s3.sh
# TODO: generate_api_key.py
# TODO: create_wx.sh, delete_wx.sh