---
- name: Load variables (main)
  include_vars: "vars/main.yml"

# TODO: create tenant
- name: "Create a tenant namespace: {{ tenantNamespace }}"
  kubernetes.core.k8s:
    name: "{{ tenantNamespace }}"
    api_version: v1
    kind: Namespace

- name: "Copy secrets to namespace: {{ tenantNamespace }}"
  shell: 'oc get secret {{ item }} -n mas-{{ mas_instance_id }}-aibroker -o yaml | sed "s/namespace: .*/namespace: {{ tenantNamespace }}/" | oc apply -f -'
  with_items:
    - km-s3-secret
    - regcred

# TODO: create_apikey.sh, delete_apikey.sh, update_apikey.sh
# TODO: create_s3.sh, delete_s3.sh
# TODO: create_wx.sh, delete_wx.sh
