---
# The following playbook is an attempt to automate the Cloud Pak for Data steps documented here:
# https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_latest/cpd/install/preinstall-overview.html

# Validate properties are provided
# -----------------------------------------------------------------------------
- name: "Load supported Cloud Pak for Data information"
  include_vars: "{{ role_path }}/../../common_vars/cp4d_supported_versions.yml"

- name: "Check that Cloud Pak for Data release version has been provided"
  assert:
    that:
      - cpd_product_version is defined and cpd_product_version != ""
    fail_msg: "Cloud Pak for Data version (cpd_product_version) is a required parameter to run this role"

- name: "Check that provided Cloud Pak for Data version is supported for MAS"
  assert:
    that:
      - cpd_product_version in cpd_supported_versions
    fail_msg: "Cloud Pak for Data version ({{ cpd_product_version }}) is not a supported version for MAS. Supported Cloud Pak for Data versions for MAS are: {{ cpd_supported_versions }}"

- name: Check that an entitlement key has been provided
  assert:
    that: cpd_entitlement_key is defined and cpd_entitlement_key != ""
    fail_msg: "ibm_entitlement_key or cpd_entitlement_key override must be provided"

# Create required namespaces
# -----------------------------------------------------------------------------
- name: "Create Cloud Pak for Data Namespaces"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/cpd_platform/namespaces.yml.j2"

# Install ibm-entitlement-key in the required namespaces
# -----------------------------------------------------------------------------
# Nothing in the cp4d base platform requires entitlement, but the services that we want to enable in CP4D do.
- name: "Install IBM Entitlement Key"
  include_tasks: "tasks/entitlement.yml"

# Install olm-utils config map
# -----------------------------------------------------------------------------
- name: "Create olm-utils config map"
  include_tasks: "tasks/create-olm-utils.yml"

# Run pre-checks
# -----------------------------------------------------------------------------
# - Assert ibm-operator-catalog is installed
# - Assert IBM Foundational Services is installed and that the version is compatible (only when CPD 4.6)
# - Assert Red Hat Certificate Manager is installed
- name: "Check Cloud Pak for Data pre-requisites"
  include_tasks: "tasks/prereq-check/main.yml"

# Auto determine Cloud Pak for Data file and block storage classes
# -----------------------------------------------------------------------------
- name: "Determine storage classes"
  include_tasks: "tasks/determine-storage-classes.yml"

# CPD 4.8 and above only: Authorizing a user to act as an IBM Cloud Pak for Data instance administrator
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-authorizing-instance-administrator
# -----------------------------------------------------------------------------
- name: "Grant permissions to {{ cpd_admin_login_sa }} service account in Cloud Pak For Data namespaces"
  include_tasks: "tasks/authorize-user-cpd-admin.yml"
  when: cpd_48_or_higher # this is only needed in CPD 4.8 and above

# CPD 4.8 and above only: Install specific catalog sources
# -----------------------------------------------------------------------------
# TODO : For now, we will need to install specific catalog sources
# for Cloud Pak for Data (cpd-platform), Foundational Services and NamespaceScope (opencloud-operators)
# until they're all into ibm-operator-catalog
- name: "Apply custom catalog sources for CPD and CPFS"
  when: (cpd_48_or_higher)
  kubernetes.core.k8s:
    apply: yes
    template: "templates/catalog_sources/{{ item }}-{{ cpd_product_version }}.yml.j2"
  with_items:
    - "cpd-platform"
    - "opencloud-operators"

# Install NamespaceScope
# -----------------------------------------------------------------------------
- include_tasks: "tasks/prereqs/install-ibm-namespace-scope.yml"

# CPD 4.8 and above only: Install IBM Licensing and Foundational Services
# -----------------------------------------------------------------------------
- when: cpd_48_or_higher
  block:
    - include_tasks: "tasks/prereqs/install-ibm-licensing.yml"
    - include_tasks: "tasks/prereqs/install-cpfs.yml"

# Install Cloud Pak for Data subscription/operator
# -----------------------------------------------------------------------------
- name: "Create Cloud Pak for Data Subscription"
  include_tasks: "tasks/create-subscriptions.yml"

# At this stage:
# - The two namespaces (ibm-cpd and ibm-cpd-operators) will be created
# - OperatorGroup will have been created in the ibm-cpd-operators namespace
# - Cloud Pak for Data Platform Operator (cpd-platform-operator-manager) will be installed in ibm-cpd-operators namespace
# - IBM Cloud Pak Foundational Services (ibm-common-service-operator) will be installed in ibm-cpd-operators namespace
# - IBM NamespaceScope Operator (ibm-namespace-scope-operator) will be installed in ibm-cpd-operators namespace
# - A NamespaceScope will have been created in the ibm-cpd-operators namespace
# - Nothing will exist in the ibm-cpd namespace yet except the entitlement key we just created

# Install Cloud Pak for Data instance
# -----------------------------------------------------------------------------
- name: "Install Cloud Pak For Data"
  include_tasks: "tasks/install-cp4d.yml"

# Debug Cloud Pak for Data installation details
# -----------------------------------------------------------------------------
- name: "Debug : Cloud Pak for Data {{ cpd_product_version }} details"
  debug:
    msg:
      - "CP4D Dashboard ......................... {{ cpd_admin_url }}"
      - "CP4D Admin Username .................... {{ cpd_admin_username }}"
      - "CP4D Admin Password .................... {{ cpd_admin_password_text }}"
