---

# 1. Delete cluster
# -----------------------------------------------------------------------------
- name: "rosa/deprovision : Delete ROSA cluster"
  when: rosa_cluster_lookup_result.rc != 1
  shell: >
    rosa delete cluster \
      --cluster-name {{ cluster_name }} \
      --mode auto \
      --yes


# 7. Watch cluster deprovisioning progress
# -----------------------------------------------------------------------------
- name: "rosa/deprovision : Wait for cluster to be deprovisioned"
  shell: rosa describe cluster -c {{ cluster_name }} -o json
  register: cluster_lookup
  failed_when: "cluster_lookup.rc > 1"
  retries: 60
  delay: 60 # 60s * 60 retries = 1 hour
  until: cluster_lookup.rc == 1


# 8. Clean up other AWS resources related to the cluster
# -----------------------------------------------------------------------------
- name: "rosa/deprovision : Clean up operator roles"
  shell: "rosa delete operator-roles -c {{ (rosa_cluster_lookup_result.stdout | from_json).id }} -m auto --yes"

- name: "rosa/deprovision : Clean up OIDC provider"
  shell: "rosa delete oidc-provider -c {{ (rosa_cluster_lookup_result.stdout | from_json).id }} -m auto --yes"
