---
# 1. Failure conditions
# -----------------------------------------------------------------------------
- name: "roks : Fail if rosa_token is not provided"
  assert:
    that: rosa_token is defined and rosa_token != ""
    fail_msg: "rosa_token property is required"


# 2. Debug Info
# -----------------------------------------------------------------------------
- name: "roks : Debug information"
  debug:
    msg:
      - "Cluster name ................. {{ cluster_name }}"
      - "OCP version .................. {{ ocp_version }}"
      - "ROSA compute nodes ........... {{ rosa_compute_nodes }}"
      - "ROSA token ................... ********************"


# 3. Check for required software
# -----------------------------------------------------------------------------
- name: "Test if rosa is installed"
  shell: rosa version
  register: rosa_version
  ignore_errors: true

- name: "Fail if rosa is not installed"
  assert:
    that: ( rosa_version.rc == 0 )
    fail_msg: "rosa CLI must be installed (https://console.redhat.com/openshift/create/rosa/welcome)"


# 4. Login
# -----------------------------------------------------------------------------
- name: "rosa : Login"
  shell: rosa login --token {{ rosa_token }}

- name: "rosa : Validate login"
  shell: rosa whoami
  register: rosa_whoami_result

- name: "rosa : Debug login"
  debug:
    msg: "{{ rosa_whoami_result }}"


# 5. Check if the cluster is already provisioned
# -----------------------------------------------------------------------------
# State: pending -> installing -> ready
- name: "rosa : Lookup Cluster"
  shell: rosa describe cluster -c {{ cluster_name }} -o json
  register: rosa_cluster_lookup_result
  failed_when: "rosa_cluster_lookup_result.rc > 1"

- name: "rosa : Debug status"
  when: rosa_cluster_lookup_result.rc == 0
  debug:
    msg: "Cluster state ......................... {{ (rosa_cluster_lookup_result.stdout | from_json).state }}"


- name: "Executig cluster {{rosa_action}} "
  include_tasks: tasks/providers/rosa/{{rosa_action}}.yml
