---

# Provide intelligent storage class selection to minimize required user knowledge

# 1. Lookup storage class availabiity
# -----------------------------------------------------------------------------
- name: "Load default storage class information"
  include_vars: "{{ role_path }}/../../common_vars/default_storage_classes.yml"

- name: Lookup storage dro
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
  register: lookup_storageclasses

- name: "Debug available storage classes"
  debug:
    msg: "{{ lookup_storageclasses | ibm.mas_devops.getResourceNames }}"


- name: "get available default storage classes"
  set_fact:
    default_storage_class: "{{ lookup_storageclasses | ibm.mas_devops.checkDefaultStorageClassAnnotation }}"

- name: "Debug available default storage classes"
  debug:
    msg: "{{ default_storage_class }}"

# # 2. Set Storage (Required)
# # -----------------------------------------------------------------------------
- name: Using available default Storage 
  when: (default_storage_class is defined) and (default_storage_class | length != 0)
  set_fact:
    dro_storage_class: "{{ lookup_storageclasses | ibm.mas_devops.defaultStorageClass(default_storage_classes_rwo) }}"

- name: Get default Storage for ROKS if not available
  when: (default_storage_class is defined) and (default_storage_class | length == 0) and (dro_storage_class is not defined or dro_storage_class == "")
  set_fact:
    dro_storage_class: "{{ lookup_storageclasses | ibm.mas_devops.defaultStorageClass(default_storage_classes_rwo) }}"

- name: Assert that storage class has been defined
  assert:
    that: dro_storage_class is defined and dro_storage_class != ""
    fail_msg: "dro_storage_class must be defined"


# 3. Debug storage class configuration
# -----------------------------------------------------------------------------
- name: "Debug DRO storage class configuration"
  debug:
    msg:
      - "Storage class (dro) .................... {{ dro_storage_class }}"

# 3. Check if storage class have default annotation
# -----------------------------------------------------------------------------
- name: add default annotation to DRO storageclass
  when: (default_storage_class is defined) and (default_storage_class | length == 0)
  kubernetes.core.k8s:
    state: patched
    api_version: storage.k8s.io/v1
    kind: StorageClass
    name: "{{ dro_storage_class }}"
    definition:
      metadata:
        annotations:
          storageclass.kubernetes.io/is-default-class: 'true'
