---
# About this task:
# Before you install IBM Cloud Pak for Data, you must install the
# IBM Cloud Pak foundational services, Certificate manager and License Service.
# This task will install only IBM Cloud Pak Foundational Services and License Service
# and will verify if Certificate Manager have been installed.
# Certificate Manager should have been installed at this point using 'cert_manager' role.

# More details: https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=cluster-installing-shared-components

# Check if and where Certificate Manager is installed
# ---------------------------------------------------------------------------------------------------
- name: "install-dependencies : Detect Certificate Manager installation"
  include_tasks: "{{ role_path }}/../../common_tasks/detect_cert_manager.yml"
  when: cert_manager_namespace is not defined or cert_manager_namespace | length == 0

#  Install Cloud Pak for Data dependency: IBM Licensing
# ---------------------------------------------------------------------------------------------------
# Set cpd-cli command to be executed
- name: "install-dependencies : Set command : Install Cloud Pak for Data dependency : IBM Licensing"
  set_fact:
    cpd_cmd_apply_cluster_components: cpd-cli manage apply-cluster-components \
      --release={{ cpd_product_version }} \
      --license_acceptance=true \
      --skip_components=ibm-cert-manager \
      --cert_manager_ns={{ cert_manager_namespace }} \
      --licensing_ns={{ cpd_ibm_licensing_namespace }} 2>&1 | tee {{ role_path }}/logs/cpd_platform_step7_cpd_install_ibm_licensing_output.log

# Debug cpd-cli command to be executed
# The output can be copied/pasted in terminal in order to re-run cpd-cli command directly for troubleshooting purposes
- name: "install-dependencies : Debug command : Install Cloud Pak for Data dependency : IBM Licensing"
  debug:
    msg:
      - "{{ cpd_cmd_apply_cluster_components | regex_replace(' \\\\', '') }}"

# Execute cpd-cli command to install IBM licensing
- name: "install-dependencies : Running command : Install Cloud Pak for Data dependency : IBM Licensing (+- 20 minutes)"
  async: 1200 # 20 minutes
  poll: 0
  shell: "{{ cpd_cmd_apply_cluster_components }}"
  register: cpd_install_ibm_licensing_output

# Wait async cpd-cli cpd-cli command to install IBM licensing
- name: "install-dependencies : Waiting command execution : Install Cloud Pak for Data dependency : IBM Foundational Services (+- 20 minutes)"
  async_status:
    jid: "{{ cpd_install_ibm_licensing_output.ansible_job_id }}"
  register: cpd_install_ibm_licensing_async_output
  until: cpd_install_ibm_licensing_async_output.finished
  retries: 15 # wait up to 15 minutes
  delay: 60
  failed_when: ('authorize-instance-topology command ran successfully' not in cpd_install_ibm_licensing_async_output.stdout)

# Debug cpd-cli command output
- name: "install-cr : Debug command output : Install Cloud Pak for Data dependency : IBM Licensing"
  debug:
    msg: "{{ cpd_install_ibm_licensing_async_output.stdout }}"

#  Install Cloud Pak for Data dependency: IBM Foundational Services
# ---------------------------------------------------------------------------------------------------
# Creates CPFS related catalog sources: opencloud-operators and cloud-native-postgresql-catalog
# Includes following subscriptions in operators namespace:
# - Foundational Services (Scaling CPFS size to small)
# - IBM Namespace Scope operator
# - Operand Deployment Lifecycle Manager

# Set cpd-cli command to be executed
- name: "install-dependencies : Set command : Install Cloud Pak for Data dependency : IBM Foundational Services"
  set_fact:
    cpd_cmd_setup_instance_topology: cpd-cli manage setup-instance-topology \
      --release={{ cpd_product_version }} \
      --cpd_operator_ns={{ cpd_operators_namespace }} \
      --cpd_instance_ns={{ cpd_instance_namespace }}  \
      --license_acceptance=true \
      --block_storage_class={{ cpd_metadata_storage_class }} 2>&1 | tee {{ role_path }}/logs/cpd_platform_step8_cpd_install_cpfs_output.log

# Debug cpd-cli command to be executed
# The output can be copied/pasted in terminal in order to re-run cpd-cli command directly for troubleshooting purposes
- name: "install-dependencies : Debug command : Install Cloud Pak for Data dependency : IBM Foundational Services"
  debug:
    msg:
      - "{{ cpd_cmd_setup_instance_topology | regex_replace(' \\\\', '') }}"

# Execute cpd-cli command to install IBM Foundational Services
- name: "install-dependencies : Running command : Install Cloud Pak for Data dependency : IBM Foundational Services (+- 20 minutes)"
  async: 1200 # 20 minutes
  poll: 0
  shell: "{{ cpd_cmd_setup_instance_topology }}"
  register: cpd_install_cpfs_output

# Wait async cpd-cli cpd-cli command to install IBM Foundational Services
- name: "install-dependencies : Waiting command execution : Install Cloud Pak for Data dependency : IBM Foundational Services (+- 20 minutes)"
  async_status:
    jid: "{{ cpd_install_cpfs_output.ansible_job_id }}"
  register: cpd_install_cpfs_async_output
  until: cpd_install_cpfs_async_output.finished
  retries: 15 # wait up to 15 minutes
  delay: 60
  failed_when: ('authorize-instance-topology command ran successfully' not in cpd_install_cpfs_async_output.stdout)

# Debug cpd-cli command output
- name: "install-dependencies : Debug command output : Install Cloud Pak for Data dependency : IBM Foundational Services"
  debug:
    msg: "{{ cpd_install_cpfs_async_output.stdout }}"
