# This task installs the pre-requisites for IBM Cloud Pak for Data platform
# -----------------------------------------------------------------------------
# Detaching an instance of IBM Cloud Pak for Data 
# from the shared operators (Upgrading from Version 4.6 to Version 4.8)
- include_tasks: "tasks/prereqs/cpd_platform/detach-shared-operators.yml"
  when: cpd_action == 'upgrade'

# Applying the required permissions to the projects (namespaces) for an instance of IBM Cloud Pak for Data instance
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-applying-required-permissions-projects-namespaces
- include_tasks: "tasks/prereqs/cpd_platform/configure-namespaces.yml"

# Updating the global image pull secret for IBM Cloud Pak for Data install
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=cluster-updating-global-image-pull-secret
- include_tasks: "tasks/prereqs/cpd_platform/configure-image-pull-policy.yml"

# Authorizing a user to act as an IBM Cloud Pak for Data instance administrator
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-authorizing-instance-administrator
- include_tasks: "tasks/prereqs/cpd_platform/authorize-user-cpd-admin.yml"

# Installing the IBM licensing for Cloud Pak for Data instance
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-installing-cloud-pak-foundational-services
- include_tasks: "tasks/prereqs/cpd_platform/configure-ibm-licensing.yml"

# Installing the IBM Cloud Pak foundational services for Cloud Pak for Data instance
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.8.x?topic=data-installing-cloud-pak-foundational-services
- include_tasks: "tasks/prereqs/cpd_platform/configure-cpfs.yml"
