# Start cpd-cli
# -----------------------------------------------------------------------------
# Login
- include_tasks: "tasks/common/login.yml"

# Install and configure cpd platform pre-reqs
- include_tasks: "tasks/prereqs/main.yml"
  # when: ('cpd_platform' in cpd_components_list)

# Install cpd-platform operator
- include_tasks: "tasks/common/install-operator.yml"
    
# Install cpd-platform custom resource
- include_tasks: "tasks/common/install-cr.yml"

# Lookup CPD credentials
- include_tasks: "tasks/common/get-cpd-details.yml"
