# Start cpd-cli
# -----------------------------------------------------------------------------
# Login
- include_tasks: "tasks/common/login.yml"
  vars:
    cpd_log_filename: "cpd_platform_step1_login_cluster"

# Install and configure cpd pre-reqs
- include_tasks: "tasks/common/install-prereqs.yml"

# Install cpd-platform operator
- include_tasks: "tasks/common/install-operator.yml"
  vars:
    cpd_log_filename: "cpd_platform_step9_install_operator"
    
# Install cpd-platform custom resource
- include_tasks: "tasks/common/install-cr.yml"
  vars:
    cpd_log_filename: "cpd_platform_step10_install_cr"

# Lookup CPD credentials
- include_tasks: "tasks/common/get-cpd-details.yml"
