# Start cpd-cli
# -----------------------------------------------------------------------------
# Create CPD namespaces
- name: "Create Cloud Pak for Data namespaces"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/cpd_platform/namespaces.yml.j2"

# Login
- include_tasks: "tasks/common/login.yml"

# Set cpd storage classes
- include_tasks: "tasks/determine-storage-classes.yml"

# Install and configure cpd platform pre-reqs
- include_tasks: "tasks/prereqs/main.yml"
  when: ('cpd_platform' in cpd_components_list)

# Install and configure cpd services pre-reqs
- include_tasks: "tasks/prereqs/cpd_services/watson_discovery.yml"
  when: ('watson_discovery' in cpd_components_list)

# Install cpd-platform operator
- include_tasks: "tasks/common/install-operator.yml"

# Install cpd-platform custom resource
- include_tasks: "tasks/common/install-cr.yml"

# Lookup CPD credentials
- include_tasks: "tasks/common/get-cpd-details.yml"
