---
# Start cpd-cli
# -----------------------------------------------------------------------------
# Login
- include_tasks: "tasks/common/login.yml"
  vars:
    cpd_log_filename: "cpd_service_{{ cpd_service_name }}_step1_login_cluster"

# Install cpd service operator
- include_tasks: "tasks/common/install-operator.yml"
  vars:
    cpd_components: "{{ cpd_service_name }}"
    cpd_log_filename: "cpd_service_{{ cpd_service_name }}_step2_install_operator"

# Install cpd service custom resource
- include_tasks: "tasks/common/install-cr.yml"
  vars:
    cpd_components: "{{ cpd_service_name }}"
    cpd_log_filename: "cpd_service_{{ cpd_service_name }}_step3_install_cr"

# Lookup CPD credentials
- include_tasks: "tasks/common/get-cpd-details.yml"
