# Start cpd-cli
# -----------------------------------------------------------------------------
# Login
- include_tasks: "tasks/common/login.yml"
  vars:
    cpd_log_filename: "cpd_platform_step1_login_cluster"

# Install and configure cpd pre-reqs for cpd_platform
- include_tasks: "tasks/common/install-prereqs.yml"
  when: ('cpd_platform' in cpd_components_list)

# Install cpd-platform operator
- include_tasks: "tasks/common/install-operator.yml"
  vars:
    cpd_log_filename: "{{ cpd_components }}_install_operator"
    
# Install cpd-platform custom resource
- include_tasks: "tasks/common/install-cr.yml"
  vars:
    cpd_log_filename: "{{ cpd_components }}_install_cr"

# Lookup CPD credentials
- include_tasks: "tasks/common/get-cpd-details.yml"
