---
# The following playbook is an attempt to automate the CP4D 4.0 / 4.5 steps documented here:
# https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_latest/cpd/install/preinstall-overview.html

# Validate properties are provided
# -----------------------------------------------------------------------------
- name: "Check that CPD release version has been provided"
  assert:
    that:
      - cpd_product_version is defined and cpd_product_version != ""
    fail_msg: "CPD version (cpd_product_version) is a required parameter to run this role"

- name: "Check that provided CPD version is supported"
  assert:
    that:
      - cpd_product_version in cpd_supported_versions
    fail_msg: "CPD version ({{ cpd_product_version }}) is not a supported CPD version. Supported CPD versions are: {{ cpd_supported_versions }}."

- name: Check that an entitlement key has been provided
  assert:
    that: cpd_entitlement_key is defined and cpd_entitlement_key != ""
    fail_msg: "ibm_entitlement_key or cpd_entitlement_key override must be provided"

# assert that the component list provided is contained within the supported component list
- name: "Check that CPD components are supported"
  when:
    - cpd_components_list is defined
  assert:
    that:
      - cpd_components_list | length > 0
      - cpd_components_supported_list | intersect(cpd_components_list) == cpd_components_list
    fail_msg: 
      - "Cloud Pak for Data Service {{ cpd_components_list | difference(cpd_components_supported_list) }} is not supported by this role."
      - "The supported components are: {{ cpd_components_supported_list }}"

# - name: "Run pre-req check"
#   include_tasks: "tasks/prereq-check.yml"

- name: "Determine storage classes"
  include_tasks: "tasks/determine-storage-classes.yml"

# Install ibm-entitlement-key in ibm-cpd namespace
# Nothing in the cp4d base platform requires entitlement, but the services that we want to enable in CP4D do.
- name: "Install IBM Entitlement Key"
  include_tasks: "tasks/entitlement.yml"

# At this stage:
# - The two namespaces (ibm-cpd and ibm-cpd-operators) will be created
# - OperatorGroup will have been created in the ibm-cpd-operators namespace
# - Cloud Pak for Data Platform Operator (cpd-platform-operator-manager) v2.0 will be installed in ibm-cpd-operators namespace
# - IBM Cloud Pak Foundational Services (ibm-common-service-operator) v3 will be installed in ibm-cpd-operators namespace
# - IBM NamespaceScope Operator (ibm-namespace-scope-operator) v3 will be installed in ibm-cpd-operators namespace
# - A NamespaceScope will have been created in the ibm-cpd-operators namespace
# - Nothing will exist in the ibm-cpd namespace yet except the entitlement key we just created

# Debug Cloud Pak for Data installation details
# -----------------------------------------------------------------------------
- name: "cpd-cli: Debug Cloud Pak for Data {{ cpd_product_version }} details"
  debug:
    msg:
      - "CP4D components  ................ {{ cpd_components_list }}"

- name: "Run install-cp4d task"
  include_tasks: "tasks/install-cp4d.yml"
