---
# The following playbook is an attempt to automate the CP4D 4.0 / 4.5 steps documented here:
# https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_latest/cpd/install/preinstall-overview.html

# Validate properties are provided
# -----------------------------------------------------------------------------
- name: "Check that CPD release version has been provided"
  assert:
    that:
      - cpd_product_version is defined and cpd_product_version != ""
    fail_msg: "CPD version (cpd_product_version) is a required parameter to run this role"

- name: "Check that provided CPD version is supported"
  assert:
    that:
      - cpd_product_version in cpd_supported_versions
    fail_msg: "CPD version ({{ cpd_product_version }}) is not a supported CPD version. Supported CPD versions are: {{ cpd_supported_versions }}."

- name: Check that an entitlement key has been provided
  assert:
    that: cpd_entitlement_key is defined and cpd_entitlement_key != ""
    fail_msg: "ibm_entitlement_key or cpd_entitlement_key override must be provided"

# assert that the component list provided is contained within the supported component list
- name: "Check that CPD components are supported"
  when:
    - cpd_components_list is defined
  assert:
    that:
      - cpd_components_list | length > 0
      - cpd_components_supported_list | sort | intersect(cpd_components_list) == cpd_components_list
    fail_msg:
      - "Cloud Pak for Data Service {{ cpd_components_list | difference(cpd_components_supported_list) }} is not supported by this role."
      - "The supported components are: {{ cpd_components_supported_list }}"

# Debug Cloud Pak for Data installation details
# -----------------------------------------------------------------------------
- name: "cpd-cli: Debug Cloud Pak for Data {{ cpd_product_version }} details"
  debug:
    msg:
      - "CP4D components  ................ {{ cpd_components_list }}"

- name: "Run install-cp4d task"
  include_tasks: "tasks/install-cp4d.yml"
