apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-sls-operators
  namespace: openshift-marketplace
spec:
  displayName: IBM SLS Catalog (Dev)
  publisher: IBM
  description: Catalog Source for IBM Suite Licensing Service (Internal Use Only)
  sourceType: grpc
  image: wiotp-docker-local.artifactory.swg-devops.com/cpopen/ibm-sls-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m