---
# mas_instance_id is required in order to be able to lookup for manage application resources
- name: "Fail if mas_instance_id is not provided"
  assert:
    that: mas_instance_id is defined and mas_instance_id != ""
    fail_msg: "mas_instance_id property is required"

# mas_workspace_id is required in order to be able to lookup for manage application resources
- name: "Fail if mas_workspace_id is not provided"
  assert:
    that: mas_workspace_id is defined and mas_workspace_id != ""
    fail_msg: "mas_workspace_id property is required"

# Configure MAP server cert for Manage attachments
# -----------------------------------------------------------------------------
- name: "Retrieve map certificates"
  include_tasks: "tasks/retrieve-map-certs.yml"
- debug:
    msg: "from main after retrieve-map-certs ran"

- name: "Add the MAP certificates in ManageWorkspace CR"
  import_role:
    name: ibm.mas_devops.suite_manage_import_certs_config
    vars:
      manage_certificates: "{{ map_tls_crt }}"
      manage_certificates_alias_prefix: "{{ map_cert_alias_prefix }}"

# 7. Restart Manage bundle pods to pick up the storage provider configuration
# ---------------------------------------------------------------------------------------------------------------------
- name: "Lookup {{ mas_app_id | capitalize }} bundle pods"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    label_selectors: mas.ibm.com/appType=serverBundle
    namespace: "mas-{{ mas_instance_id }}-{{ mas_app_id }}"
  register: manage_bundle_output

- name: "List {{ mas_app_id | capitalize }} bundle pods"
  vars:
    list: []
  set_fact:
    list: "{{ list + [item.metadata.name] }}"
  with_items: "{{ manage_bundle_output.resources }}"
  no_log: true

- debug:
    msg: "Restarting the following {{ mas_app_id | capitalize }} bundle pods: {{ list }}"

- name: "Restart {{ mas_app_id | capitalize }} bundle pods to apply the attachments configuration"
  failed_when:
    - manage_bundle_output.resources | length == 0
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Pod
    name: "{{ item.metadata.name }}"
    label_selectors: mas.ibm.com/appType=serverBundle
    namespace: "mas-{{ mas_instance_id }}-manage"
  with_items: "{{ manage_bundle_output.resources  }}"
  loop_control:
    label: "Restarting bundle pod: {{ item.metadata.name }}..."

- name: "Pause for 1 minute before checking bundle pods..."
  pause:
    seconds: 60

- name: "Wait {{ mas_app_id | capitalize }} bundle pods to be ready"
  include_tasks: tasks/wait_bundle_pods.yml
